"""What the website chat knows about each procedure on Dental Haven's service list.

For each procedure: the words patients use (English/Tagalog/Taglish) and short, general answers to the
questions patients ask most: what it is, how long it takes, does it hurt, recovery, and how long it lasts.
Everything is general information with typical ranges ("usually", "about"); the dentist confirms the
details for each patient. No prices here (those come from Administration → Price list).
Edit freely: add keywords, adjust times to match how Dental Haven actually works.
"""

def _p(key, service, name, kw, what, duration=None, pain=None, recovery=None, lasts=None):
    return {"key": key, "service": service, "name": name, "kw": kw, "what": what, "duration": duration,
            "pain": pain, "recovery": recovery, "lasts": lasts}


NUMB_EN = "It's done with local anesthesia, so the area is numb; you may feel pressure but it shouldn't hurt."
NUMB_TL = "Ginagawa ito nang may local anesthesia kaya manhid ang bahagi; pressure lang ang mararamdaman, hindi sakit."

PROCEDURES = [
    # ------------------------------------------------------------------ Preventive & Diagnostic
    _p("checkup", "general-dentistry", "Check-up & consultation",
       ["check-up", "checkup", "check up", "consultation", "consult", "konsulta", "patingin", "exam", "examination"],
       {"en": "A check-up is a full examination of your teeth, gums and mouth, with X-rays if needed, so your dentist can spot problems early and explain your options.",
        "tl": "Ang check-up ay kumpletong pagsusuri ng ngipin, gilagid at bibig, may X-ray kung kailangan, para maagapan ng dentista ang problema at maipaliwanag ang mga opsyon."},
       {"en": "A check-up usually takes about 20 to 30 minutes, or about 45 to 60 minutes together with a cleaning.",
        "tl": "Karaniwang 20 hanggang 30 minuto ang check-up, o mga 45 hanggang 60 minuto kung kasama ang cleaning."},
       {"en": "A check-up doesn't hurt: it's a gentle look at your teeth and gums.", "tl": "Hindi po masakit ang check-up: marahang pagtingin lang ito sa ngipin at gilagid."},
       {"en": "There's no recovery time. You can go back to your normal day right away.", "tl": "Walang recovery time. Puwede na kayong bumalik agad sa normal na gawain."}),
    _p("cleaning", "general-dentistry", "Cleaning (oral prophylaxis)",
       ["cleaning", "linis", "magpalinis", "prophylaxis", "prophy", "scaling and polishing", "tartar", "plaque", "oral prophylaxis"],
       {"en": "A professional cleaning (oral prophylaxis) removes plaque and hardened tartar with scaling, then polishes your teeth so they're smoother and harder for plaque to stick to.",
        "tl": "Ang professional cleaning (oral prophylaxis) ay pagtanggal ng plaque at tartar sa pamamagitan ng scaling, saka pinapakinis ang ngipin para mas mahirap kapitan ng plaque."},
       {"en": "A cleaning usually takes about 30 to 60 minutes in one visit, depending on how much tartar there is.",
        "tl": "Karaniwang 30 hanggang 60 minuto ang cleaning, isang balik lang, depende sa dami ng tartar."},
       {"en": "Most people feel only mild scraping or vibration. If your gums are sensitive, tell your dentist and they'll go gently.",
        "tl": "Karamihan ay nakakaramdam lang ng bahagyang pagkayod o vibration. Kung sensitive ang gilagid, sabihin sa dentista para dahan-dahan."},
       {"en": "No downtime. Your gums may feel a little tender for a day. Most people repeat it every 6 months.",
        "tl": "Walang downtime. Puwedeng bahagyang maselan ang gilagid nang isang araw. Karaniwang inuulit tuwing 6 na buwan."}),
    _p("xray", "general-dentistry", "Dental X-rays (panoramic, cephalometric, CBCT)",
       ["x-ray", "xray", "x ray", "panoramic", "pano", "cephalometric", "ceph", "cbct", "3d scan", "cone beam", "imaging"],
       {"en": "Dental X-rays show what can't be seen in the mouth: panoramic shows all your teeth and jaws, cephalometric shows the side of the head for braces planning, and CBCT gives a detailed 3D view for implants, wisdom teeth and complex cases.",
        "tl": "Ipinapakita ng dental X-ray ang hindi nakikita sa bibig: panoramic para sa lahat ng ngipin at panga, cephalometric para sa pagpaplano ng braces, at CBCT para sa detalyadong 3D view para sa implants, wisdom tooth at komplikadong kaso."},
       {"en": "It's quick: the scan itself takes less than a minute, and the whole visit for an X-ray usually takes only a few minutes.",
        "tl": "Mabilis lang po: wala pang isang minuto ang mismong scan, at ilang minuto lang ang buong X-ray."},
       {"en": "X-rays are painless. You just stand or sit still for a few seconds.", "tl": "Hindi masakit ang X-ray. Tatayo o uupo lang kayo nang ilang segundo."},
       {"en": "No recovery needed. Dental X-rays use a low dose of radiation; tell us if you're pregnant.", "tl": "Walang recovery. Mababa ang radiation ng dental X-ray; sabihin po kung buntis kayo."}),
    _p("fluoride", "general-dentistry", "Fluoride treatment",
       ["fluoride", "varnish"],
       {"en": "A high-concentration fluoride is painted on the teeth to strengthen enamel, help prevent decay, and reverse very early weak spots.",
        "tl": "Pinapahid ang mataas na konsentrasyon ng fluoride sa ngipin para tumibay ang enamel, maiwasan ang pagkabulok, at maayos ang maagang mahihinang bahagi."},
       {"en": "It takes only a few minutes, usually right after a cleaning.", "tl": "Ilang minuto lang po, kadalasan pagkatapos ng cleaning."},
       {"en": "It's painless: it's simply brushed or painted on.", "tl": "Hindi masakit: pinapahid lang ito."},
       {"en": "Avoid eating, drinking hot drinks and brushing for a few hours afterwards, as your dentist advises.", "tl": "Iwasan muna ang pagkain, mainit na inumin at pagsisipilyo nang ilang oras pagkatapos, ayon sa payo ng dentista."}),
    _p("sealant", "general-dentistry", "Dental sealants",
       ["sealant", "sealants", "pit and fissure"],
       {"en": "Sealants are thin protective coatings on the chewing surfaces of the back teeth (molars). They seal the deep grooves where cavities often start.",
        "tl": "Ang sealant ay manipis na pananggalang sa nginunguyang bahagi ng bagang. Tinatakpan nito ang malalalim na uka kung saan kadalasang nagsisimula ang butas."},
       {"en": "It takes just a few minutes per tooth, all in one visit.", "tl": "Ilang minuto lang bawat ngipin, sa isang balik lang."},
       {"en": "It's painless: no drilling and no injections.", "tl": "Hindi masakit: walang drilling at walang turok."},
       {"en": "You can eat normally right after.", "tl": "Puwede nang kumain nang normal pagkatapos."},
       {"en": "Sealants can last several years; your dentist checks them at each check-up and touches them up if needed.", "tl": "Tumatagal ang sealant nang ilang taon; tinitingnan ito sa bawat check-up at inaayos kung kailangan."}),
    _p("cancer_screening", "general-dentistry", "Oral cancer screening",
       ["oral cancer", "cancer screening", "cancer", "bukol sa bibig", "lump in mouth", "mouth sore", "singaw na hindi gumagaling"],
       {"en": "The dentist examines your lips, tongue, cheeks, gums and throat for any unusual patches, sores or lumps, so problems can be found early.",
        "tl": "Sinusuri ng dentista ang labi, dila, pisngi, gilagid at lalamunan para sa anumang kakaibang mantsa, sugat o bukol, para maagapan."},
       {"en": "It takes only a few minutes and is usually part of your check-up.", "tl": "Ilang minuto lang po, at kadalasang kasama sa check-up."},
       {"en": "It's painless: a visual check and gentle touch.", "tl": "Hindi masakit: tinitingnan at marahang hinahawakan lang."},
       {"en": "No recovery needed. If a sore doesn't heal within 2 weeks, have it checked.", "tl": "Walang recovery. Kung may sugat na hindi gumagaling sa loob ng 2 linggo, magpa-check po."}),
    # ------------------------------------------------------------------ Restorative
    _p("filling", "restorative-dentistry", "Tooth filling",
       ["filling", "fillings", "pasta", "magpapasta", "cavity", "cavities", "butas", "sira ang ngipin", "composite", "amalgam"],
       {"en": "A filling removes the decayed part of a tooth and restores it, usually with tooth-colored composite that's matched to your tooth shade.",
        "tl": "Sa pasta, tinatanggal ang sirang bahagi ng ngipin at pinupunan ito, kadalasan ng tooth-colored composite na kakulay ng inyong ngipin."},
       {"en": "A filling usually takes about 20 to 60 minutes per tooth, in one visit, depending on its size.",
        "tl": "Karaniwang 20 hanggang 60 minuto bawat ngipin ang pasta, isang balik lang, depende sa laki."},
       {"en": "Small fillings may not need numbing; for deeper ones, local anesthesia keeps you comfortable.",
        "tl": "Ang maliit na pasta ay puwedeng hindi na kailangan ng anesthesia; sa malalim, may anesthesia para komportable kayo."},
       {"en": "Wait until the numbness wears off before eating (1 to 3 hours). Mild sensitivity for a few days is normal.",
        "tl": "Hintaying mawala ang pamamanhid bago kumain (1 hanggang 3 oras). Normal ang bahagyang pangingilo nang ilang araw."},
       {"en": "With good care, fillings can last many years. Regular check-ups help them last longer.", "tl": "Kung maaalagaan, tumatagal ang pasta nang maraming taon. Nakakatulong ang regular na check-up."}),
    _p("crown", "restorative-dentistry", "Dental crown",
       ["crown", "crowns", "jacket", "cap", "zirconia", "pfm", "porcelain fused"],
       {"en": "A crown is a custom-made cap that covers the whole tooth to restore its shape, strength and appearance, often after a large filling, a crack, or a root canal.",
        "tl": "Ang crown (jacket) ay pasadyang takip sa buong ngipin para maibalik ang hugis, tibay at itsura nito, kadalasan pagkatapos ng malaking pasta, bitak, o root canal."},
       {"en": "A crown usually takes 2 visits: one to prepare the tooth and take a scan or impression, and one to fit the final crown. Each visit is about 1 hour. Our in-house lab helps shorten the wait in between.",
        "tl": "Karaniwang 2 balik ang crown: una para ihanda ang ngipin at kunan ng scan o impression, at pangalawa para ikabit ang crown. Mga 1 oras bawat balik. Nakakatulong ang sarili naming lab na mapabilis ang paghihintay."},
       {"en": NUMB_EN, "tl": NUMB_TL},
       {"en": "The tooth may feel a little sensitive for a few days. You can eat normally once the final crown is fitted.",
        "tl": "Puwedeng bahagyang mangilo ang ngipin nang ilang araw. Puwede nang kumain nang normal kapag naikabit na ang crown."},
       {"en": "With good care and regular check-ups, a crown can last many years, often 10 years or more.", "tl": "Kung maaalagaan at regular ang check-up, tumatagal ang crown nang maraming taon, kadalasan 10 taon o higit pa."}),
    _p("bridge", "restorative-dentistry", "Dental bridge",
       ["bridge", "bridges", "tulay", "fixed bridge"],
       {"en": "A bridge replaces one or more missing teeth with a fixed false tooth, anchored to crowns on the natural teeth beside the gap.",
        "tl": "Pinapalitan ng bridge ang nawalang ngipin gamit ang nakakabit na pekeng ngipin, nakakapit sa crowns sa katabing ngipin."},
       {"en": "A bridge usually takes 2 or more visits over about 1 to 2 weeks: preparing the teeth and taking a scan, then fitting the bridge.",
        "tl": "Karaniwang 2 o higit pang balik sa loob ng 1 hanggang 2 linggo: paghahanda ng ngipin at scan, saka pagkakabit ng bridge."},
       {"en": NUMB_EN, "tl": NUMB_TL},
       {"en": "Expect some sensitivity for a few days. Clean under the bridge daily with a floss threader or water flosser.",
        "tl": "Normal ang pangingilo nang ilang araw. Linisin araw-araw ang ilalim ng bridge gamit ang floss threader o water flosser."},
       {"en": "With good care, a bridge can last 10 years or more.", "tl": "Kung maaalagaan, tumatagal ang bridge nang 10 taon o higit pa."}),
    _p("inlay", "restorative-dentistry", "Inlays & onlays",
       ["inlay", "onlay", "inlays", "onlays"],
       {"en": "Inlays and onlays are lab-made fillings for larger areas of decay or damage on the chewing surface: stronger than a regular filling, but more conservative than a crown.",
        "tl": "Ang inlay at onlay ay pasta na gawa sa lab para sa mas malaking sira sa nginunguyang bahagi: mas matibay kaysa karaniwang pasta, pero mas konserbatibo kaysa crown."},
       {"en": "Usually 2 visits: one to prepare the tooth and take a scan, and one to bond the inlay or onlay.",
        "tl": "Karaniwang 2 balik: una para ihanda ang ngipin at kunan ng scan, pangalawa para ikabit ang inlay o onlay."},
       {"en": NUMB_EN, "tl": NUMB_TL},
       {"en": "Mild sensitivity for a few days is normal; you can eat normally once it's bonded.", "tl": "Normal ang bahagyang pangingilo nang ilang araw; puwede nang kumain nang normal kapag naikabit na."},
       {"en": "With good care, inlays and onlays can last many years.", "tl": "Kung maaalagaan, tumatagal ito nang maraming taon."}),
    _p("root_canal", "restorative-dentistry", "Root canal therapy",
       ["root canal", "rct", "endodontic", "endo", "patay na ugat", "nerve", "pulp"],
       {"en": "A root canal removes infected or inflamed pulp from inside the tooth, cleans and seals it, relieving pain and saving the natural tooth instead of pulling it.",
        "tl": "Sa root canal, tinatanggal ang namamaga o may impeksyong laman (pulp) sa loob ng ngipin, nililinis at sinasara, para mawala ang sakit at mailigtas ang ngipin sa halip na bunutin."},
       {"en": "A root canal usually takes 1 to 3 visits of about 60 to 90 minutes each, depending on the tooth. A crown is often placed afterwards.",
        "tl": "Karaniwang 1 hanggang 3 balik ang root canal, mga 60 hanggang 90 minuto bawat isa, depende sa ngipin. Madalas nilalagyan ng crown pagkatapos."},
       {"en": "With local anesthesia, most people say it feels like getting a filling. It actually relieves the toothache.",
        "tl": "May anesthesia, kaya sabi ng karamihan ay parang nagpapasta lang. Ito pa nga ang nagpapawala ng sakit ng ngipin."},
       {"en": "The tooth may be tender for a few days; avoid chewing hard food on it until it's fully restored.", "tl": "Puwedeng maselan ang ngipin nang ilang araw; iwasang ngumuya ng matigas dito hangga't hindi pa tapos ang restoration."},
       {"en": "A root-canal-treated tooth with a good crown can last many years, even a lifetime with good care.", "tl": "Ang ngiping na-root canal na may maayos na crown ay tumatagal nang maraming taon, kahit habambuhay kung maaalagaan."}),
    # ------------------------------------------------------------------ Prosthodontics & Tooth Replacement
    _p("denture", "prosthodontics", "Dentures (complete & partial)",
       ["denture", "dentures", "pustiso", "false teeth", "flexite", "flexible denture", "partial denture", "complete denture", "full denture"],
       {"en": "Dentures are removable replacements for missing teeth and the surrounding gum. Complete dentures replace all teeth in an arch; partial dentures fill the gaps between your natural teeth.",
        "tl": "Ang pustiso ay natatanggal na kapalit ng nawalang ngipin at gilagid. Ang complete denture ay para sa lahat ng ngipin sa isang panga; ang partial ay para sa mga puwang sa pagitan ng natural na ngipin."},
       {"en": "Dentures usually take several visits over a few weeks: impressions or scans, bite records, a try-in, then delivery and adjustments. Our in-house lab helps shorten the process.",
        "tl": "Karaniwang ilang balik sa loob ng ilang linggo ang pustiso: impression o scan, pagkuha ng kagat, try-in, at saka pagbibigay at pag-aadjust. Nakakatulong ang sarili naming lab na mapabilis ito."},
       {"en": "Making dentures doesn't hurt. New dentures can cause some sore spots at first, which we adjust.", "tl": "Hindi masakit ang paggawa ng pustiso. Puwedeng may mangalay na bahagi sa umpisa, na inaayos namin."},
       {"en": "Getting used to new dentures usually takes a few weeks. Start with soft food, and come back for adjustments if anything rubs.",
        "tl": "Karaniwang ilang linggo ang pag-aadjust sa bagong pustiso. Magsimula sa malambot na pagkain, at bumalik para sa adjustment kung may kumikiskis."},
       {"en": "Dentures often last 5 to 10 years; they may need relining as your gums change over time.", "tl": "Karaniwang 5 hanggang 10 taon ang pustiso; puwedeng kailanganin ng reline habang nagbabago ang gilagid."}),
    _p("implant", "prosthodontics", "Dental implant",
       ["implant", "implants", "tanim na ngipin", "titanium"],
       {"en": "A dental implant is a titanium post placed in the jawbone that acts like a tooth root. It supports a crown, bridge or denture that looks and works like a natural tooth.",
        "tl": "Ang dental implant ay titanium na turnilyo na itinatanim sa buto ng panga, na parang ugat ng ngipin. Sinusuportahan nito ang crown, bridge o pustiso na parang natural na ngipin."},
       {"en": "Placing an implant usually takes about 1 to 2 hours. The bone then needs about 3 to 6 months to bond with it before the final crown is attached, so the whole process takes a few months.",
        "tl": "Karaniwang 1 hanggang 2 oras ang paglalagay ng implant. Kailangan ng buto ng mga 3 hanggang 6 na buwan para kumapit dito bago ikabit ang crown, kaya ilang buwan ang kabuuang proseso."},
       {"en": "The implant is placed under local anesthesia, so you feel pressure, not pain. Mild soreness for a few days afterwards is normal.",
        "tl": "May local anesthesia kaya pressure lang ang mararamdaman, hindi sakit. Normal ang bahagyang kirot nang ilang araw pagkatapos."},
       {"en": "Most people return to normal activities in 1 to 2 days. Eat soft food on the other side for about a week and keep the area clean.",
        "tl": "Karamihan ay nakakabalik sa normal na gawain sa loob ng 1 hanggang 2 araw. Kumain ng malambot sa kabilang side nang mga isang linggo at panatilihing malinis."},
       {"en": "With good care, an implant can last many years, often a lifetime. The crown on top may need replacing after many years.", "tl": "Kung maaalagaan, tumatagal ang implant nang maraming taon, kadalasan habambuhay. Ang crown sa ibabaw ay puwedeng palitan pagkalipas ng maraming taon."}),
    _p("veneer", "prosthodontics", "Veneers",
       ["veneer", "veneers", "emax", "e.max", "porcelain veneer", "composite veneer"],
       {"en": "Veneers are thin shells of porcelain or composite bonded to the front of the teeth to improve their color, shape, small gaps or chips.",
        "tl": "Ang veneers ay manipis na porcelain o composite na idinidikit sa harap ng ngipin para gumanda ang kulay, hugis, maliit na siwang o tapyas."},
       {"en": "Composite veneers are often done in 1 visit (a few hours for several teeth). Porcelain veneers usually take 2 to 3 visits over about 1 to 2 weeks.",
        "tl": "Ang composite veneers ay kadalasang natatapos sa 1 balik (ilang oras para sa ilang ngipin). Ang porcelain veneers ay karaniwang 2 hanggang 3 balik sa loob ng 1 hanggang 2 linggo."},
       {"en": "Little or no discomfort. If some enamel needs shaping, the area can be numbed.", "tl": "Kaunti o walang discomfort. Kung kailangang hubugin ang enamel, puwedeng mag-anesthesia."},
       {"en": "No real downtime. Some sensitivity for a few days is normal; avoid biting very hard things like ice.", "tl": "Halos walang downtime. Normal ang pangingilo nang ilang araw; iwasan ang pagkagat sa sobrang tigas gaya ng yelo."},
       {"en": "Composite veneers often last about 5 to 7 years, porcelain veneers 10 years or more with good care.", "tl": "Ang composite veneers ay karaniwang 5 hanggang 7 taon, ang porcelain ay 10 taon o higit pa kung maaalagaan."}),
    # ------------------------------------------------------------------ Orthodontics & TMJ
    _p("braces", "orthodontics", "Braces",
       ["braces", "brace", "brackets", "bracket", "metal braces", "ceramic braces", "ortho", "magpabrace", "magpa-brace"],
       {"en": "Braces use metal or ceramic brackets and wires to gradually move teeth into better positions and correct bite problems.",
        "tl": "Gumagamit ang braces ng metal o ceramic na brackets at wire para unti-unting maiayos ang ngipin at ang kagat."},
       {"en": "Putting on braces takes about 1 to 2 hours. Treatment usually lasts about 1 to 3 years, with adjustment visits about every month (around 20 to 30 minutes each).",
        "tl": "Mga 1 hanggang 2 oras ang pagkakabit ng braces. Karaniwang 1 hanggang 3 taon ang treatment, may adjustment mga buwan-buwan (mga 20 hanggang 30 minuto bawat isa)."},
       {"en": "Putting braces on doesn't hurt. Teeth may feel sore for a few days after placement and after adjustments; soft food and pain relievers your dentist recommends help.",
        "tl": "Hindi masakit ang pagkakabit. Puwedeng mangalay ang ngipin nang ilang araw pagkakabit at pagka-adjust; nakakatulong ang malambot na pagkain at gamot na irerekomenda ng dentista."},
       {"en": "Soreness usually settles in 3 to 5 days. Avoid hard and sticky food, and brush carefully around the brackets.", "tl": "Karaniwang nawawala ang pangangalay sa 3 hanggang 5 araw. Iwasan ang matigas at malagkit na pagkain, at maingat na magsipilyo sa paligid ng brackets."},
       {"en": "The results last when you wear your retainer as instructed after braces.", "tl": "Tatagal ang resulta kung susuotin ang retainer ayon sa bilin pagkatapos ng braces."}),
    _p("aligners", "orthodontics", "Clear aligners",
       ["aligner", "aligners", "invisalign", "clear aligner", "invisible braces", "clear braces"],
       {"en": "Clear aligners are removable, custom-made clear trays that gradually straighten the teeth. You switch to a new set every week or two.",
        "tl": "Ang clear aligners ay natatanggal at pasadyang malinaw na tray na unti-unting nag-aayos ng ngipin. Nagpapalit ng bagong set tuwing isa o dalawang linggo."},
       {"en": "Treatment usually takes about 6 months to 2 years depending on the case, with check-ups every 6 to 8 weeks. Aligners must be worn about 20 to 22 hours a day.",
        "tl": "Karaniwang 6 na buwan hanggang 2 taon ang treatment depende sa kaso, may check-up tuwing 6 hanggang 8 linggo. Kailangang suotin ang aligners nang mga 20 hanggang 22 oras bawat araw."},
       {"en": "You'll feel pressure for a day or two with each new set, which means they're working. Most people find them comfortable.",
        "tl": "May pressure nang isa o dalawang araw sa bawat bagong set, senyales na gumagana. Komportable ito para sa karamihan."},
       {"en": "No downtime. Remove them to eat and brush, then put them back on.", "tl": "Walang downtime. Tanggalin kapag kakain at magsisipilyo, saka ibalik."},
       {"en": "Results last when you wear your retainer as instructed afterwards.", "tl": "Tatagal ang resulta kung susuotin ang retainer ayon sa bilin pagkatapos."}),
    _p("retainer", "orthodontics", "Retainers",
       ["retainer", "retainers"],
       {"en": "A retainer is a custom appliance worn after braces or aligners to keep the teeth from moving back.",
        "tl": "Ang retainer ay pasadyang appliance na sinusuot pagkatapos ng braces o aligners para hindi bumalik sa dating puwesto ang ngipin."},
       {"en": "Getting a retainer takes a short visit for a scan or impression and another to fit it. Most people wear it full-time at first, then at night, as the dentist advises.",
        "tl": "Maikling balik para sa scan o impression at isa pa para isukat ito. Karaniwang buong araw muna ang pagsuot, saka tuwing gabi, ayon sa payo ng dentista."},
       {"en": "It may feel tight for a few days, then comfortable.", "tl": "Puwedeng masikip nang ilang araw, saka magiging komportable."},
       {"en": "No downtime. Clean it daily and keep it in its case when not wearing it.", "tl": "Walang downtime. Linisin araw-araw at ilagay sa lalagyan kapag hindi suot."},
       {"en": "With care, a retainer can last several years; bring it to your check-ups.", "tl": "Kung maaalagaan, tumatagal ang retainer nang ilang taon; dalhin ito sa check-up."}),
    _p("tmj", "orthodontics", "TMJ (jaw joint) care",
       ["tmj", "jaw pain", "masakit ang panga", "panga", "jaw clicking", "lock jaw", "clicking jaw", "jaw joint"],
       {"en": "TMJ care treats problems of the jaw joint, like jaw pain, clicking, limited opening or headaches from clenching. Care may include a night guard, bite adjustment, exercises and habit advice.",
        "tl": "Ang TMJ care ay para sa problema sa kasukasuan ng panga, gaya ng sakit sa panga, lagitik, hirap bumuka o sakit ng ulo dahil sa pagngangalit. Puwedeng kasama ang night guard, pag-aayos ng kagat, ehersisyo at payo sa gawi."},
       {"en": "The first TMJ consultation usually takes about 30 to 45 minutes. Treatment length depends on the cause.",
        "tl": "Karaniwang 30 hanggang 45 minuto ang unang TMJ consultation. Ang haba ng treatment ay depende sa dahilan."},
       {"en": "The examination is gentle. Treatment aims to relieve your discomfort.", "tl": "Marahan ang pagsusuri. Layunin ng treatment na maibsan ang sakit."},
       None),
    # ------------------------------------------------------------------ Oral Surgery
    _p("extraction", "oral-surgery", "Tooth extraction",
       ["extraction", "extract", "bunot", "magpabunot", "pabunot", "pull tooth", "tooth removal", "remove a tooth", "tanggal ngipin", "bunutin"],
       {"en": "An extraction is the safe removal of a tooth that can't be saved, for example because of severe decay, trauma, crowding, or in preparation for braces.",
        "tl": "Ang bunot ay ligtas na pagtanggal ng ngiping hindi na maililigtas, halimbawa dahil sa matinding sira, pinsala, siksikan, o bilang paghahanda sa braces."},
       {"en": "A simple extraction usually takes about 20 to 40 minutes, including the time for the anesthesia to work. A surgical extraction can take longer.",
        "tl": "Karaniwang 20 hanggang 40 minuto ang simpleng bunot, kasama na ang paghihintay na umepekto ang anesthesia. Mas matagal ang surgical na bunot."},
       {"en": NUMB_EN + " Some soreness afterwards is normal and usually eased with the pain reliever your dentist recommends.",
        "tl": NUMB_TL + " Normal ang kirot pagkatapos, na karaniwang naiibsan ng gamot na irerekomenda ng dentista."},
       {"en": "Most people feel better in 2 to 3 days, and the gum heals in about 1 to 2 weeks. Bite on gauze for 30 to 45 minutes, and for 24 hours avoid spitting, straws and smoking; eat soft food.",
        "tl": "Karamihan ay gumagaan ang pakiramdam sa loob ng 2 hanggang 3 araw, at naghihilom ang gilagid sa 1 hanggang 2 linggo. Kagatin ang gauze nang 30 hanggang 45 minuto; sa loob ng 24 oras, iwasan ang pagdura, straw at paninigarilyo; kumain ng malambot."}),
    _p("wisdom", "oral-surgery", "Wisdom tooth removal",
       ["wisdom", "wisdom tooth", "wisdom teeth", "wisdom tooth removal", "wisdom tooth extraction", "wisdom teeth removal", "odontectomy", "impacted", "third molar", "bagang sa dulo"],
       {"en": "Wisdom tooth removal (third molar surgery) takes out impacted or problematic wisdom teeth. A panoramic or 3D CBCT X-ray is used to plan it safely.",
        "tl": "Ang wisdom tooth removal (odontectomy) ay pagtanggal ng impacted o may problemang wisdom tooth. Ginagamitan ito ng panoramic o 3D CBCT X-ray para ligtas na maplano."},
       {"en": "It usually takes about 30 to 60 minutes per tooth, depending on its position.",
        "tl": "Karaniwang 30 hanggang 60 minuto bawat ngipin, depende sa posisyon nito."},
       {"en": NUMB_EN + " Swelling and soreness for a few days afterwards are normal.", "tl": NUMB_TL + " Normal ang pamamaga at kirot nang ilang araw pagkatapos."},
       {"en": "Swelling usually peaks around day 2 to 3; most people go back to school or work in 2 to 5 days. Use cold compresses, eat soft food, and follow your dentist's instructions.",
        "tl": "Karaniwang pinakamaga sa ika-2 hanggang ika-3 araw; karamihan ay nakakabalik sa eskwela o trabaho sa 2 hanggang 5 araw. Gumamit ng cold compress, kumain ng malambot, at sundin ang bilin ng dentista."}),
    _p("bone_graft", "oral-surgery", "Bone grafting",
       ["bone graft", "bone grafting", "graft", "kulang ang buto", "bone loss"],
       {"en": "Bone grafting rebuilds or regenerates bone in the jaw, usually so there's enough bone to hold a dental implant.",
        "tl": "Ang bone grafting ay pagpapatibay o pagpaparami ng buto sa panga, kadalasan para may sapat na buto na kakapitan ng implant."},
       {"en": "The procedure usually takes about 30 to 90 minutes. The graft then needs a few months to heal before an implant is placed.",
        "tl": "Karaniwang 30 hanggang 90 minuto ang procedure. Ilang buwan ang paghilom ng graft bago ilagay ang implant."},
       {"en": NUMB_EN, "tl": NUMB_TL},
       {"en": "Expect mild swelling and soreness for a few days. Eat soft food and follow your aftercare instructions.", "tl": "Asahan ang bahagyang pamamaga at kirot nang ilang araw. Kumain ng malambot at sundin ang bilin pagkatapos."}),
    # ------------------------------------------------------------------ Cosmetic Dentistry
    _p("whitening", "aesthetic-dentistry", "Teeth whitening",
       ["whitening", "whiten", "bleaching", "bleach", "pampaputi", "paputi", "magpaputi", "yellow teeth", "madilaw"],
       {"en": "Professional whitening brightens stained or discolored natural teeth, either in the clinic or with custom take-home trays.",
        "tl": "Ang professional whitening ay nagpapaputi ng may mantsa o kupas na natural na ngipin, sa clinic man o gamit ang pasadyang take-home tray."},
       {"en": "In-office whitening usually takes about 1 to 1.5 hours in one visit. Take-home whitening is used daily for about 1 to 2 weeks.",
        "tl": "Karaniwang 1 hanggang 1.5 oras ang in-office whitening, isang balik lang. Ang take-home ay ginagamit araw-araw nang mga 1 hanggang 2 linggo."},
       {"en": "Whitening doesn't hurt, but some people feel temporary sensitivity for a day or two.", "tl": "Hindi masakit ang whitening, pero may ilang nakakaramdam ng pansamantalang pangingilo nang isa o dalawang araw."},
       {"en": "No downtime. For 48 hours, avoid coffee, tea, colas and other staining food and drinks.", "tl": "Walang downtime. Sa loob ng 48 oras, iwasan ang kape, tsaa, soft drinks at iba pang nakakamantsa."},
       {"en": "Results often last several months to a couple of years, depending on your habits; touch-ups help.", "tl": "Karaniwang tumatagal ang resulta nang ilang buwan hanggang ilang taon, depende sa gawi; nakakatulong ang touch-up."}),
    _p("bonding", "aesthetic-dentistry", "Dental bonding",
       ["bonding", "chipped", "chip", "natapyas", "tapyas", "small gap", "siwang"],
       {"en": "Bonding uses tooth-colored resin to repair chips, cracks or small gaps and reshape teeth, usually without drilling.",
        "tl": "Gumagamit ang bonding ng tooth-colored resin para ayusin ang tapyas, bitak o maliit na siwang at hubugin ang ngipin, kadalasan nang walang drilling."},
       {"en": "Bonding usually takes about 30 to 60 minutes per tooth, in one visit.", "tl": "Karaniwang 30 hanggang 60 minuto bawat ngipin ang bonding, isang balik lang."},
       {"en": "It's usually painless and often needs no anesthesia.", "tl": "Kadalasang hindi masakit at madalas hindi na kailangan ng anesthesia."},
       {"en": "No downtime. Avoid biting hard objects with the bonded tooth.", "tl": "Walang downtime. Iwasang kumagat ng matigas gamit ang ngiping na-bonding."},
       {"en": "Bonding often lasts several years and can be touched up.", "tl": "Karaniwang tumatagal ang bonding nang ilang taon at puwedeng ayusin."}),
    _p("makeover", "aesthetic-dentistry", "Smile makeover",
       ["smile makeover", "makeover", "smile design", "full smile", "gandahan ang ngiti"],
       {"en": "A smile makeover is a personalized plan that combines treatments such as whitening, bonding, veneers, crowns or braces to enhance your whole smile.",
        "tl": "Ang smile makeover ay personal na plano na pinagsasama ang mga treatment gaya ng whitening, bonding, veneers, crowns o braces para gumanda ang buong ngiti."},
       {"en": "It depends on the treatments in your plan: from a few visits over a couple of weeks to several months if braces are included. Your dentist gives you a timeline at the consultation.",
        "tl": "Depende sa mga treatment sa inyong plano: mula ilang balik sa loob ng ilang linggo hanggang ilang buwan kung may braces. Bibigyan kayo ng timeline sa konsulta."},
       {"en": "Most cosmetic treatments involve little discomfort, and anesthesia is used when needed.", "tl": "Kaunti lang ang discomfort sa karamihan ng cosmetic treatment, at may anesthesia kung kailangan."},
       None),
    # ------------------------------------------------------------------ Periodontal (Gum) Care
    _p("deep_cleaning", "periodontal-care", "Scaling and root planing (deep cleaning)",
       ["deep cleaning", "deep clean", "root planing", "scaling and root planing", "periodontitis", "gum disease", "periodontal", "loose teeth", "umuuga"],
       {"en": "Scaling and root planing is a deep cleaning below the gumline that removes tartar and bacteria from the roots to treat gum disease (periodontitis) and help the gums heal.",
        "tl": "Ang scaling and root planing ay malalim na paglilinis sa ilalim ng gilagid para tanggalin ang tartar at bacteria sa ugat, para gamutin ang sakit sa gilagid (periodontitis) at makatulong sa paghilom."},
       {"en": "It's usually done in 1 to 2 visits (often half of the mouth at a time), about 45 to 90 minutes each.",
        "tl": "Karaniwang 1 hanggang 2 balik (kadalasan kalahati ng bibig bawat balik), mga 45 hanggang 90 minuto bawat isa."},
       {"en": "The area is numbed with local anesthesia so you stay comfortable.", "tl": "May local anesthesia kaya komportable kayo."},
       {"en": "Gums may be tender and teeth a bit sensitive for a few days. Your dentist will check how your gums have healed after a few weeks.",
        "tl": "Puwedeng maselan ang gilagid at mangilo ang ngipin nang ilang araw. Titingnan ng dentista ang paghilom pagkalipas ng ilang linggo."}),
    _p("gum_graft", "periodontal-care", "Gum grafting",
       ["gum graft", "gum grafting", "receding gum", "receding gums", "umuurong na gilagid", "gum recession", "exposed root"],
       {"en": "Gum grafting covers exposed tooth roots from receding gums, reducing sensitivity and protecting the roots.",
        "tl": "Tinatakpan ng gum grafting ang lumabas na ugat ng ngipin dahil sa umuurong na gilagid, para mabawasan ang pangingilo at maprotektahan ang ugat."},
       {"en": "The procedure usually takes about 1 to 2 hours.", "tl": "Karaniwang 1 hanggang 2 oras ang procedure."},
       {"en": NUMB_EN, "tl": NUMB_TL},
       {"en": "Initial healing takes about 1 to 2 weeks; eat soft food and follow your aftercare instructions carefully.", "tl": "Mga 1 hanggang 2 linggo ang unang paghilom; kumain ng malambot at sundin nang mabuti ang bilin."}),
    # ------------------------------------------------------------------ Pediatrics & Special Care
    _p("sdf", "pediatric-dentistry", "Silver diamine fluoride (SDF)",
       ["sdf", "silver diamine", "silver fluoride"],
       {"en": "SDF is a liquid brushed onto a cavity to help stop it from getting bigger, with no drilling. The decayed part turns dark permanently.",
        "tl": "Ang SDF ay likidong pinapahid sa butas ng ngipin para hindi na lumaki, nang walang drilling. Nagiging maitim nang permanente ang sirang bahagi."},
       {"en": "It takes just a few minutes.", "tl": "Ilang minuto lang po."},
       {"en": "It's painless: no drilling and no injections.", "tl": "Hindi masakit: walang drilling at walang turok."},
       {"en": "No downtime. It may need to be reapplied at later check-ups.", "tl": "Walang downtime. Puwedeng kailanganing ulitin sa susunod na check-up."}),
    _p("kids_crown", "pediatric-dentistry", "Crowns for kids",
       ["crown for kids", "kids crown", "crowns for kids", "stainless crown", "child crown", "baby tooth crown"],
       {"en": "A crown for a child's tooth covers and protects a baby tooth with large decay so it can stay until the adult tooth is ready.",
        "tl": "Ang crown para sa bata ay tumatakip at nagpoprotekta sa gatas na ngipin na malaki ang sira, para manatili ito hanggang handa na ang permanenteng ngipin."},
       {"en": "It's usually done in one visit of about 30 to 60 minutes.", "tl": "Karaniwang isang balik lang, mga 30 hanggang 60 minuto."},
       {"en": "The tooth is numbed so your child stays comfortable; sedation can be discussed for very anxious children.", "tl": "Pinapamanhid ang ngipin para komportable ang bata; puwedeng pag-usapan ang sedation para sa sobrang kinakabahang bata."},
       {"en": "Your child can usually go back to normal activities the same day.", "tl": "Karaniwang nakakabalik sa normal na gawain ang bata sa parehong araw."}),
    _p("sedation", "pediatric-dentistry", "Conscious sedation",
       ["sedation", "sedate", "pampatulog", "special needs", "autism", "autistic"],
       {"en": "Conscious sedation helps very anxious children and patients with special needs relax during treatment. The patient stays awake but calm, and is monitored throughout.",
        "tl": "Tumutulong ang conscious sedation na kumalma ang sobrang kinakabahang bata at pasyenteng may special needs habang ginagamot. Gising pero kalmado ang pasyente, at binabantayan sa buong treatment."},
       {"en": "It adds time for preparation and monitoring before and after the treatment; your dentist will explain the plan and any fasting instructions.",
        "tl": "May dagdag na oras para sa paghahanda at pagbabantay bago at pagkatapos ng treatment; ipapaliwanag ng dentista ang plano at kung kailangang mag-ayuno."},
       {"en": "Sedation helps the patient feel relaxed and comfortable.", "tl": "Tumutulong ang sedation na maging relaxed at komportable ang pasyente."},
       {"en": "The patient may feel drowsy for a few hours and should go home with an adult.", "tl": "Puwedeng antukin ang pasyente nang ilang oras at dapat may kasamang adult pauwi."}),
]


# ---------------------------------------------------------------------------------------------------
# More answers per procedure: how to prepare, what to avoid afterwards, risks/side effects, alternatives,
# whether a consultation/X-ray comes first ("before"), and when to call the clinic ("contact").
# Procedures without their own text use GENERIC below.
# ---------------------------------------------------------------------------------------------------

GENERIC = {
    "prepare": {"en": "Usually no special preparation is needed. Eat a light meal and brush your teeth before you come, bring a list of the medicines you take, and tell the dentist about any allergies or health conditions.",
                "tl": "Kadalasan walang espesyal na paghahanda. Kumain nang magaan at magsipilyo bago pumunta, dalhin ang listahan ng gamot na iniinom, at sabihin sa dentista kung may allergy o karamdaman."},
    "avoid": {"en": "Your dentist will give you instructions afterwards. In general, don't eat until any numbness wears off, and avoid very hard, sticky or very hot food for the first day.",
              "tl": "Bibigyan kayo ng dentista ng bilin pagkatapos. Sa pangkalahatan, huwag munang kumain hangga't manhid pa, at iwasan ang sobrang tigas, malagkit o sobrang init na pagkain sa unang araw."},
    "risks": {"en": "Like any treatment, it can have side effects, usually mild and temporary, such as sensitivity or soreness. Your dentist will explain the specific risks for your case before starting.",
              "tl": "Tulad ng anumang treatment, may posibleng side effects, kadalasang banayad at pansamantala, gaya ng pangingilo o kirot. Ipapaliwanag ng dentista ang mga panganib para sa inyong kaso bago magsimula."},
    "alternatives": {"en": "There are often other options. Your dentist will explain the alternatives, with their pros and cons, so you can choose what suits you.",
                     "tl": "Kadalasan may iba pang opsyon. Ipapaliwanag ng dentista ang mga alternatibo, pati ang pros at cons, para makapili kayo ng bagay sa inyo."},
    "before": {"en": "Yes: every treatment starts with a consultation and exam. X-rays are taken when needed so your dentist can plan safely.",
               "tl": "Opo: nagsisimula ang bawat treatment sa konsulta at pagsusuri. Kumukuha ng X-ray kung kailangan para ligtas na maplano ng dentista."},
    "contact": {"en": "Call the branch if pain or swelling gets worse instead of better after 2 to 3 days, if bleeding doesn't stop, if you get a fever, or if something feels wrong, like a loose filling or crown. For severe swelling or trouble breathing or swallowing, go to the nearest emergency room.",
                "tl": "Tumawag sa branch kung lumalala ang sakit o pamamaga sa halip na gumaan pagkalipas ng 2 hanggang 3 araw, kung hindi tumitigil ang dugo, kung nilagnat, o kung may kakaiba, gaya ng natanggal na pasta o crown. Kung matindi ang pamamaga o hirap huminga o lumunok, pumunta agad sa emergency room."},
}

EXTRA = {
    "extraction": {
        "prepare": {"en": "Eat a light meal before your appointment (unless told otherwise), bring your list of medicines, and tell your dentist if you take blood thinners, are pregnant, or have diabetes, heart or bleeding problems. An X-ray is usually taken first.",
                    "tl": "Kumain nang magaan bago ang appointment (maliban kung iba ang bilin), dalhin ang listahan ng gamot, at sabihin sa dentista kung umiinom ng pampalabnaw ng dugo, buntis, o may diabetes, sakit sa puso o problema sa pagdurugo. Karaniwang nagpapa-X-ray muna."},
        "avoid": {"en": "For the first 24 hours: no spitting hard, rinsing, straws, smoking or alcohol. Eat soft, cool food (like porridge, yogurt, mashed food) and chew on the other side for a few days; avoid hot, spicy, hard or crunchy food.",
                  "tl": "Sa unang 24 oras: bawal ang malakas na pagdura, pagmumog, straw, paninigarilyo at alak. Kumain ng malambot at malamig (gaya ng lugaw, yogurt, dinurog na pagkain) at ngumuya sa kabilang side nang ilang araw; iwasan ang mainit, maanghang, matigas o malutong."},
        "risks": {"en": "Possible side effects include bleeding for a few hours, swelling, soreness, and occasionally a painful 'dry socket' if the blood clot comes out. Following the aftercare instructions lowers these risks.",
                  "tl": "Posibleng side effects ang pagdurugo nang ilang oras, pamamaga, kirot, at paminsan-minsan ang masakit na 'dry socket' kapag natanggal ang namuong dugo. Nababawasan ito kapag sinunod ang bilin pagkatapos."},
        "alternatives": {"en": "If the tooth can be saved, a filling, crown or root canal may be an option instead. If it's removed, the gap can be replaced with an implant, bridge or denture.",
                         "tl": "Kung maililigtas pa ang ngipin, puwedeng pasta, crown o root canal sa halip na bunot. Kung bubunutin, mapapalitan ang puwang ng implant, bridge o pustiso."},
        "before": {"en": "Yes: the dentist examines the tooth first, and an X-ray is usually taken to see the roots and plan a safe extraction.",
                   "tl": "Opo: sinusuri muna ang ngipin, at karaniwang may X-ray para makita ang ugat at maplano ang ligtas na pagbunot."},
        "contact": {"en": "Call the branch if bleeding doesn't slow down after biting on gauze for an hour, if pain gets worse after day 2 to 3, or if you get a fever or bad taste. Go to the ER for heavy bleeding that won't stop or trouble breathing or swallowing.",
                    "tl": "Tumawag sa branch kung hindi humihina ang dugo kahit kinagat na ang gauze nang isang oras, kung lumalala ang sakit pagkalipas ng ika-2 hanggang ika-3 araw, o kung nilagnat o may mapait na lasa. Pumunta sa ER kung malakas na pagdurugo na hindi tumitigil o hirap huminga o lumunok."},
    },
    "wisdom": {
        "prepare": {"en": "A panoramic or CBCT X-ray is taken first to plan the surgery. Eat a light meal before (unless told otherwise), arrange a ride home if you're sedated, and stock up on soft food for the next few days.",
                    "tl": "Kumukuha muna ng panoramic o CBCT X-ray para maplano ang surgery. Kumain nang magaan bago (maliban kung iba ang bilin), magpasundo kung may sedation, at maghanda ng malambot na pagkain para sa susunod na mga araw."},
        "avoid": {"en": "For a few days, avoid straws, smoking, spitting, strenuous exercise, and hard, crunchy, spicy or very hot food. Eat soft food and keep the area clean as instructed.",
                  "tl": "Sa loob ng ilang araw, iwasan ang straw, paninigarilyo, pagdura, mabigat na ehersisyo, at matigas, malutong, maanghang o sobrang init na pagkain. Kumain ng malambot at panatilihing malinis ayon sa bilin."},
        "risks": {"en": "Common side effects are swelling, soreness and limited opening for a few days. Less commonly there can be dry socket, infection, or temporary numbness of the lip or tongue; 3D X-rays help lower these risks.",
                  "tl": "Karaniwang side effects ang pamamaga, kirot at hirap bumuka nang ilang araw. Mas bihira ang dry socket, impeksyon, o pansamantalang pamamanhid ng labi o dila; nakakatulong ang 3D X-ray na mabawasan ang mga ito."},
        "alternatives": {"en": "If a wisdom tooth is healthy and not causing problems, your dentist may recommend monitoring it with regular check-ups instead of removing it.",
                         "tl": "Kung maayos ang wisdom tooth at walang problema, puwedeng irekomenda ng dentista na bantayan na lang ito sa regular na check-up sa halip na tanggalin."},
        "before": {"en": "Yes: a consultation and a panoramic or 3D CBCT X-ray are needed to see the tooth's position and nearby nerves.",
                   "tl": "Opo: kailangan ng konsulta at panoramic o 3D CBCT X-ray para makita ang posisyon ng ngipin at ang malapit na ugat."},
    },
    "root_canal": {
        "avoid": {"en": "Don't eat until the numbness wears off, and avoid chewing hard food on that tooth until it has its final filling or crown.",
                  "tl": "Huwag kumain hangga't manhid pa, at iwasang ngumuya ng matigas sa ngiping iyon hangga't wala pang final na pasta o crown."},
        "risks": {"en": "The tooth may be tender for a few days. Occasionally a tooth needs retreatment, and a root-canal-treated tooth can be more brittle, which is why a crown is often recommended.",
                  "tl": "Puwedeng maselan ang ngipin nang ilang araw. Paminsan-minsan kailangang ulitin ang treatment, at mas marupok ang ngiping na-root canal, kaya kadalasang inirerekomenda ang crown."},
        "alternatives": {"en": "The main alternative is extracting the tooth, then replacing it with an implant, bridge or denture. Saving your natural tooth is usually the better option when possible.",
                         "tl": "Ang pangunahing alternatibo ay bunutin ang ngipin at palitan ng implant, bridge o pustiso. Kadalasang mas mainam na mailigtas ang natural na ngipin kung posible."},
        "before": {"en": "Yes: an exam and X-ray are needed to check the tooth's roots and infection before treatment.",
                   "tl": "Opo: kailangan ng pagsusuri at X-ray para makita ang ugat at impeksyon bago ang treatment."},
    },
    "implant": {
        "prepare": {"en": "You'll have a consultation and a 3D CBCT scan first. Tell your dentist about your health, medicines and whether you smoke, since smoking and uncontrolled diabetes affect healing.",
                    "tl": "May konsulta at 3D CBCT scan muna. Sabihin sa dentista ang inyong kalusugan, mga gamot at kung naninigarilyo, dahil nakakaapekto sa paghilom ang paninigarilyo at hindi kontroladong diabetes."},
        "avoid": {"en": "For the first days, eat soft food on the other side, avoid smoking, alcohol and strenuous exercise, and don't press on the area.",
                  "tl": "Sa mga unang araw, kumain ng malambot sa kabilang side, iwasan ang paninigarilyo, alak at mabigat na ehersisyo, at huwag diinan ang bahagi."},
        "risks": {"en": "As with any surgery, there can be swelling, bruising or discomfort for a few days. Less commonly, infection or an implant that doesn't bond with the bone. Careful 3D planning and good aftercare lower these risks.",
                  "tl": "Tulad ng anumang surgery, puwedeng may pamamaga, pasa o kirot nang ilang araw. Mas bihira ang impeksyon o implant na hindi kumapit sa buto. Nababawasan ito ng maingat na 3D planning at maayos na pag-aalaga."},
        "alternatives": {"en": "Alternatives to an implant include a fixed bridge or a removable denture. Your dentist will compare them with you.",
                         "tl": "Ang alternatibo sa implant ay fixed bridge o natatanggal na pustiso. Ikukumpara ito ng dentista kasama ninyo."},
        "before": {"en": "Yes: a consultation and a 3D CBCT scan are needed to check the bone and plan the implant position. Some patients need bone grafting first.",
                   "tl": "Opo: kailangan ng konsulta at 3D CBCT scan para matingnan ang buto at maplano ang posisyon ng implant. May pasyenteng kailangan munang mag-bone grafting."},
    },
    "filling": {
        "avoid": {"en": "Avoid eating until the numbness wears off so you don't bite your cheek or tongue. If the tooth feels sensitive, avoid very hot or cold food for a few days.",
                  "tl": "Huwag munang kumain hangga't manhid para hindi makagat ang pisngi o dila. Kung nangingilo, iwasan ang sobrang init o lamig nang ilang araw."},
        "alternatives": {"en": "For very large cavities, an inlay, onlay or crown may be stronger. For very early decay, fluoride may be enough; for young children, SDF can stop some cavities without drilling.",
                         "tl": "Sa napakalaking butas, mas matibay ang inlay, onlay o crown. Sa napakaagang sira, puwedeng sapat na ang fluoride; sa maliliit na bata, napipigilan ng SDF ang ilang butas nang walang drilling."},
    },
    "crown": {
        "avoid": {"en": "With a temporary crown, avoid sticky and hard food and chew on the other side. Once the final crown is fitted, eat normally but avoid biting very hard things like ice.",
                  "tl": "Kapag temporary crown pa, iwasan ang malagkit at matigas at ngumuya sa kabilang side. Kapag naikabit na ang final crown, kumain nang normal pero iwasan ang pagkagat sa sobrang tigas gaya ng yelo."},
        "alternatives": {"en": "Depending on the tooth, an onlay or a large filling may be an option; for front teeth, a veneer may work if the tooth is healthy.",
                         "tl": "Depende sa ngipin, puwedeng onlay o malaking pasta; sa ngipin sa harap, puwedeng veneer kung malusog ang ngipin."},
    },
    "braces": {
        "avoid": {"en": "Avoid hard, sticky and chewy food (like nuts, hard candy, chicharon, gum and caramel), cut food into small pieces, and don't bite on pens or nails.",
                  "tl": "Iwasan ang matigas, malagkit at makunat na pagkain (gaya ng mani, matigas na kendi, chicharon, bubble gum at caramel), hiwain nang maliit ang pagkain, at huwag kagatin ang ballpen o kuko."},
        "alternatives": {"en": "Clear aligners are a nearly invisible, removable alternative for many cases. For small gaps or uneven edges, veneers or bonding may help.",
                         "tl": "Ang clear aligners ay halos hindi halata at natatanggal na alternatibo para sa maraming kaso. Sa maliit na siwang o hindi pantay na gilid, puwedeng veneers o bonding."},
        "before": {"en": "Yes: a consultation, photos, a scan or impressions, and X-rays (panoramic and cephalometric) are used to plan your braces.",
                   "tl": "Opo: may konsulta, litrato, scan o impression, at X-ray (panoramic at cephalometric) para maplano ang braces."},
    },
    "aligners": {
        "alternatives": {"en": "Traditional braces work for all types of cases and don't depend on wearing trays; your dentist will say which suits you.",
                         "tl": "Ang traditional braces ay para sa lahat ng uri ng kaso at hindi nakadepende sa pagsuot ng tray; sasabihin ng dentista kung alin ang bagay sa inyo."},
        "before": {"en": "Yes: a consultation, a 3D scan and X-rays are needed to plan your aligners.", "tl": "Opo: kailangan ng konsulta, 3D scan at X-ray para maplano ang aligners."},
    },
    "whitening": {
        "prepare": {"en": "Have a check-up and cleaning first: whitening works best on clean teeth, and cavities or gum problems should be treated first.",
                    "tl": "Magpa-check-up at cleaning muna: mas maganda ang whitening sa malinis na ngipin, at dapat gamutin muna ang butas o problema sa gilagid."},
        "avoid": {"en": "For 48 hours, avoid coffee, tea, colas, red wine, soy sauce, and other staining food and drinks, and don't smoke.",
                  "tl": "Sa loob ng 48 oras, iwasan ang kape, tsaa, soft drinks, red wine, toyo at iba pang nakakamantsa, at huwag manigarilyo."},
        "risks": {"en": "Temporary tooth sensitivity or mild gum irritation for a day or two is common. Whitening doesn't change the color of crowns, veneers or fillings.",
                  "tl": "Karaniwan ang pansamantalang pangingilo o bahagyang iritasyon ng gilagid nang isa o dalawang araw. Hindi nagbabago ng kulay ang crowns, veneers o pasta."},
        "alternatives": {"en": "For stains that whitening can't fix, veneers or bonding can change the color and shape of teeth.",
                         "tl": "Para sa mantsang hindi naaalis ng whitening, puwedeng veneers o bonding para mabago ang kulay at hugis ng ngipin."},
    },
    "deep_cleaning": {
        "avoid": {"en": "Avoid eating until the numbness wears off, and for a day or two avoid very hot, spicy or hard food. Brush gently but thoroughly.",
                  "tl": "Huwag munang kumain hangga't manhid, at sa isa o dalawang araw iwasan ang sobrang init, maanghang o matigas. Magsipilyo nang marahan pero masinsinan."},
        "risks": {"en": "Gums may be tender and teeth may feel sensitive for a few days. As the gums heal and tighten, teeth can look slightly longer.",
                  "tl": "Puwedeng maselan ang gilagid at mangilo ang ngipin nang ilang araw. Habang humihilom at humihigpit ang gilagid, puwedeng magmukhang bahagyang mas mahaba ang ngipin."},
    },
    "denture": {
        "avoid": {"en": "At first, avoid sticky, very hard or chewy food, cut food into small pieces, and chew on both sides. Don't sleep with dentures unless your dentist says so.",
                  "tl": "Sa umpisa, iwasan ang malagkit, sobrang tigas o makunat na pagkain, hiwain nang maliit, at ngumuya sa magkabilang side. Huwag matulog nang suot ang pustiso maliban kung sinabi ng dentista."},
        "alternatives": {"en": "Alternatives include dental implants (fixed) or a bridge; implants can also hold dentures more firmly.",
                         "tl": "Ang alternatibo ay dental implants (nakakabit) o bridge; puwede ring gamitin ang implants para mas kumapit ang pustiso."},
    },
    "veneer": {
        "alternatives": {"en": "Depending on your goal, whitening, bonding, braces or aligners, or a crown may be alternatives.",
                         "tl": "Depende sa inyong layunin, puwedeng whitening, bonding, braces o aligners, o crown ang alternatibo."},
    },
    "cleaning": {
        "prepare": {"en": "No special preparation: brush and floss as usual before you come.", "tl": "Walang espesyal na paghahanda: magsipilyo at mag-floss gaya ng dati bago pumunta."},
        "avoid": {"en": "You can eat right away. If fluoride was applied, wait about 30 minutes, or as your dentist advises.", "tl": "Puwede nang kumain agad. Kung nilagyan ng fluoride, maghintay ng mga 30 minuto, o ayon sa payo ng dentista."},
        "before": {"en": "A cleaning usually comes with a check-up; X-rays are taken only when needed.", "tl": "Kadalasang kasama ng cleaning ang check-up; nagpapa-X-ray lang kung kailangan."},
    },
    "bone_graft": {
        "avoid": {"en": "For a few days, eat soft food, avoid chewing on the area, and avoid smoking, straws and strenuous exercise.",
                  "tl": "Sa loob ng ilang araw, kumain ng malambot, huwag nguyain ang bahagi, at iwasan ang paninigarilyo, straw at mabigat na ehersisyo."},
        "before": {"en": "Yes: a 3D CBCT scan is used to measure the bone and plan the graft.", "tl": "Opo: ginagamit ang 3D CBCT scan para masukat ang buto at maplano ang graft."},
    },
    "gum_graft": {
        "avoid": {"en": "For 1 to 2 weeks, eat soft, cool food, don't brush or floss the graft area until told, and avoid smoking.",
                  "tl": "Sa loob ng 1 hanggang 2 linggo, kumain ng malambot at malamig, huwag sipilyuhin o i-floss ang bahaging na-graft hangga't hindi sinasabi, at iwasan ang paninigarilyo."},
    },
    "kids_crown": {
        "prepare": {"en": "Talk about the visit in a positive way, bring a favorite toy, and let the dentist know about your child's health and any medicines.",
                    "tl": "Pag-usapan ang pagbisita nang positibo, magdala ng paboritong laruan, at sabihin sa dentista ang kalusugan at gamot ng bata."},
    },
    "sedation": {
        "prepare": {"en": "Follow the fasting instructions your dentist gives, wear comfortable clothes, and make sure a responsible adult brings the patient home.",
                    "tl": "Sundin ang bilin ng dentista tungkol sa pag-aayuno, magsuot ng komportableng damit, at siguraduhing may kasamang responsableng adult pauwi."},
        "risks": {"en": "Sedation is monitored throughout. Drowsiness, dizziness or nausea for a few hours can happen; your dentist will review the patient's health first to make sure it's safe.",
                  "tl": "Binabantayan ang sedation sa buong treatment. Puwedeng antukin, mahilo o maduwal nang ilang oras; titingnan muna ng dentista ang kalusugan ng pasyente para masiguradong ligtas."},
    },
}

for _p_ in PROCEDURES:
    _p_.update(EXTRA.get(_p_["key"], {}))


# ---------------------------------------------------------------------------------------------------
# Materials. Where Dental Haven's service list names materials, those are used; otherwise the answer lists
# common options and says the dentist confirms what's available (please adjust to the clinic's actual materials).
# ---------------------------------------------------------------------------------------------------
GENERIC["materials"] = {
    "en": "The material depends on the treatment, the tooth, and your needs and budget. Your dentist will show you the options, how they look and last, and how they affect the cost, so you can choose together.",
    "tl": "Ang materyales ay depende sa treatment, sa ngipin, at sa inyong pangangailangan at budget. Ipapakita ng dentista ang mga opsyon, ang itsura at tibay, at epekto sa halaga, para makapili kayo nang magkasama."}

MATERIALS = {
    "filling": {"en": "We restore teeth with tooth-colored composite resin (matched to your tooth shade) or amalgam (silver-colored, very durable). Temporary fillings use a soft temporary material until the final restoration. Composite fillings often last about 5 to 10 years, amalgam about 10 to 15 years with good care.",
                "tl": "Pinupunan namin ang ngipin ng tooth-colored composite resin (kakulay ng ngipin) o amalgam (kulay pilak, napakatibay). Ang temporary na pasta ay gawa sa malambot na pansamantalang materyales hanggang sa final restoration. Karaniwang 5 hanggang 10 taon ang composite at 10 hanggang 15 taon ang amalgam kung maaalagaan."},
    "crown": {"en": "Common crown materials are zirconia (very strong, natural-looking), all-ceramic or porcelain (most natural for front teeth), porcelain-fused-to-metal, and full metal. Temporary crowns are made of acrylic or composite and worn for a short time. Your dentist will confirm which options suit your tooth; the material affects the look, strength and cost.",
              "tl": "Karaniwang materyales ng crown ang zirconia (napakatibay at natural ang itsura), all-ceramic o porcelain (pinaka-natural sa ngipin sa harap), porcelain-fused-to-metal, at purong metal. Ang temporary crown ay gawa sa acrylic o composite at pansamantala lang. Kukumpirmahin ng dentista kung alin ang bagay sa inyong ngipin; nakakaapekto ang materyales sa itsura, tibay at halaga."},
    "bridge": {"en": "Bridges are commonly made of zirconia, all-ceramic, or porcelain-fused-to-metal, like crowns. Your dentist will recommend the best material for the location and your bite.",
               "tl": "Karaniwang gawa ang bridge sa zirconia, all-ceramic, o porcelain-fused-to-metal, gaya ng crown. Irerekomenda ng dentista ang pinakamainam na materyales para sa puwesto at kagat ninyo."},
    "inlay": {"en": "Inlays and onlays are commonly made of ceramic or composite resin, crafted to fit the tooth precisely.",
              "tl": "Karaniwang gawa ang inlay at onlay sa ceramic o composite resin, ginawa para eksaktong kumasya sa ngipin."},
    "denture": {"en": "Dentures are commonly made of acrylic (a sturdy plastic) with acrylic or composite teeth. Partial dentures can be flexible (nylon-based, no metal clasps) or have a metal framework for extra strength. Your dentist will explain which suits you.",
                "tl": "Karaniwang gawa ang pustiso sa acrylic (matibay na plastik) na may acrylic o composite na ngipin. Ang partial na pustiso ay puwedeng flexible (nylon, walang metal na kawit) o may metal na frame para mas matibay. Ipapaliwanag ng dentista kung alin ang bagay sa inyo."},
    "implant": {"en": "Dental implants are titanium posts, a strong, body-friendly metal that bonds with bone. The crown on top is usually zirconia or porcelain.",
                "tl": "Ang dental implant ay titanium na turnilyo, isang matibay na metal na hiyang sa katawan at kumakapit sa buto. Ang crown sa ibabaw ay kadalasang zirconia o porcelain."},
    "veneer": {"en": "Veneers are made of porcelain (very natural-looking and stain-resistant, often lasting 10+ years) or composite resin (done in fewer visits, easy to repair, often lasting about 5 to 7 years).",
               "tl": "Ang veneers ay gawa sa porcelain (napaka-natural ng itsura at hindi madaling mamantsahan, madalas 10+ taon) o composite resin (mas kaunting balik, madaling ayusin, madalas 5 hanggang 7 taon)."},
    "braces": {"en": "Braces use metal (stainless steel) or ceramic (tooth-colored) brackets, with metal wires and small elastic bands. Ceramic brackets are less noticeable.",
               "tl": "Gumagamit ang braces ng metal (stainless steel) o ceramic (kakulay ng ngipin) na brackets, may metal na wire at maliliit na goma. Mas hindi halata ang ceramic."},
    "aligners": {"en": "Clear aligners are made of a thin, clear medical-grade plastic, custom-made for your teeth. Yes, we offer clear aligners.",
                 "tl": "Ang clear aligners ay gawa sa manipis at malinaw na medical-grade na plastik, pasadya para sa inyong ngipin. Opo, mayroon kaming clear aligners."},
    "retainer": {"en": "Retainers are either clear plastic (removable), acrylic with a wire (removable), or a thin wire bonded behind the teeth (fixed).",
                 "tl": "Ang retainer ay puwedeng clear na plastik (natatanggal), acrylic na may wire (natatanggal), o manipis na wire na nakadikit sa likod ng ngipin (nakakabit)."},
    "bonding": {"en": "Bonding uses tooth-colored composite resin, shaded to match your teeth.", "tl": "Gumagamit ang bonding ng tooth-colored composite resin na kakulay ng inyong ngipin."},
    "sealant": {"en": "Sealants are made of a thin, tooth-colored or clear resin coating.", "tl": "Ang sealant ay manipis na resin na kakulay ng ngipin o malinaw."},
    "kids_crown": {"en": "Crowns for baby teeth are commonly stainless steel (very durable) or tooth-colored options for front teeth.",
                   "tl": "Ang crown para sa gatas na ngipin ay kadalasang stainless steel (napakatibay) o tooth-colored para sa ngipin sa harap."},
    "whitening": {"en": "Professional whitening uses peroxide-based gels, applied safely by the dentist in the clinic or with custom trays at home.",
                  "tl": "Gumagamit ang professional whitening ng peroxide-based na gel, ligtas na inilalapat ng dentista sa clinic o gamit ang pasadyang tray sa bahay."},
    "root_canal": {"en": "After cleaning, the canals are filled with a rubber-like material (gutta-percha) and sealed; the tooth is then restored with a filling or crown.",
                   "tl": "Pagkatapos linisin, pinupunan ang mga canal ng parang-gomang materyales (gutta-percha) at sinasara; saka nilalagyan ng pasta o crown ang ngipin."},
    "bone_graft": {"en": "Bone grafts use biocompatible graft material that your body gradually replaces with your own bone. Your dentist will explain the type used for your case.",
                   "tl": "Gumagamit ang bone graft ng biocompatible na materyales na unti-unting napapalitan ng sariling buto. Ipapaliwanag ng dentista ang uri para sa inyong kaso."},
}
for _p_ in PROCEDURES:
    if _p_["key"] in MATERIALS:
        _p_["materials"] = MATERIALS[_p_["key"]]
