"""Common patient questions for the website chat (English + Tagalog).

Each entry: key, keywords (phrases patients might type, English/Tagalog/Taglish), answer in English and
Tagalog, and an optional service slug (so "Book" pre-fills that service). Answers are general
information only: no prices, no clinic policies the clinic hasn't confirmed, no medical advice.
Clinic-specific things we don't know yet (HMO, discounts, payment options) are sent to the branch.
"""

FAQ = [
    {"key": "careers", "service": "",
     "kw": ["hiring", "careers", "career", "job", "jobs", "vacancy", "vacancies", "job opening", "apply for", "apply as", "job application",
            "resume", "cv", "work for you", "work with you", "work at dental haven", "naghahanap ng trabaho", "trabaho", "hiring ba", "may bakante",
            "internship", "intern", "ojt", "bakanteng posisyon", "open position", "posisyon"],
     "en": "We're always glad to hear from dentists, dental assistants, dental technicians and front-desk staff! At Dental Haven you'll get "
           "training for dentists and staff, work with innovative tools and equipment, and practice digital dentistry every day with our own "
           "digital dental lab. Send your CV to {careers_email}, with the position and the branch you're interested in.",
     "tl": "Masaya po kaming makatanggap ng aplikasyon mula sa mga dentista, dental assistant, dental technician at front-desk staff! Sa Dental Haven, "
           "may training para sa mga dentista at staff, gumagamit kami ng makabagong tools at equipment, at digital dentistry ang araw-araw naming "
           "ginagawa kasama ang sarili naming digital dental lab. Ipadala po ang inyong CV sa {careers_email}, kasama ang posisyon at branch na gusto ninyo."},
    {"key": "hurt", "service": "",
     "kw": ["does it hurt", "will it hurt", "painful ba", "masakit ba", "sasakit ba", "is it painful", "pain during", "anesthesia", "anesthesia",
            "turok", "injection", "numb", "manhid"],
     "en": "Most treatments are done with local anesthesia, so the area is numb and you should feel pressure rather than pain. "
           "If you're nervous, tell your dentist: they'll explain each step and go at your pace.",
     "tl": "Karamihan ng treatment ay ginagawa nang may local anesthesia, kaya manhid ang bahagi at pressure lang ang mararamdaman, hindi sakit. "
           "Kung kinakabahan kayo, sabihin lang po sa dentista: ipapaliwanag nila ang bawat hakbang at dahan-dahan lang."},
    {"key": "nervous", "service": "",
     "kw": ["takot", "natatakot", "scared", "afraid", "nervous", "anxious", "anxiety", "kinakabahan", "phobia", "kaba"],
     "en": "You're not alone: many patients feel nervous about the dentist. Our team takes it slowly, explains everything first, and you can ask to pause anytime. "
           "For children and patients with special needs, conscious sedation is also available when appropriate.",
     "tl": "Hindi po kayo nag-iisa: marami ang kinakabahan sa dentista. Dahan-dahan ang aming team, ipinapaliwanag muna ang lahat, at puwede kayong humingi ng pahinga anumang oras. "
           "Para sa mga bata at pasyenteng may special needs, may conscious sedation din kung angkop."},
    {"key": "cleaning_often", "service": "general-dentistry",
     "kw": ["how often cleaning", "how often should", "gaano kadalas", "every 6 months", "every six months", "ilang beses", "how often check"],
     "en": "Most people should have a check-up and professional cleaning every 6 months. Some patients, like those with gum problems or braces, may need it more often. "
           "Your dentist will tell you what's right for you.",
     "tl": "Karaniwan po, tuwing 6 na buwan ang check-up at professional cleaning. May mga pasyenteng kailangan nang mas madalas, gaya ng may problema sa gilagid o naka-braces. "
           "Sasabihin ng dentista kung ano ang tama para sa inyo."},
    {"key": "cleaning_long", "service": "general-dentistry",
     "kw": ["how long cleaning", "how long does cleaning", "gaano katagal ang cleaning", "gaano katagal linis", "cleaning takes", "how long is the cleaning"],
     "en": "A check-up and cleaning usually takes about 30 to 60 minutes, depending on how much tartar needs to be removed.",
     "tl": "Karaniwang 30 hanggang 60 minuto po ang check-up at cleaning, depende sa dami ng tartar na kailangang tanggalin."},
    {"key": "extraction_after", "service": "oral-surgery",
     "kw": ["after extraction", "after tooth extraction", "pagkatapos bunot", "pagkatapos ng bunot", "after bunot", "bagong bunot", "aftercare",
            "after pulling", "can i eat after", "puwede na kumain", "pwede na kumain"],
     "en": "After an extraction: bite on the gauze for 30 to 45 minutes; for the first 24 hours don't spit hard, rinse, use a straw or smoke; "
           "eat soft, cool food and chew on the other side; a cold compress helps with swelling. "
           "Call the branch if the bleeding doesn't stop, or if pain or swelling gets worse after 2 to 3 days.",
     "tl": "Pagkatapos magpabunot: kagatin ang gauze nang 30 hanggang 45 minuto; sa unang 24 oras, huwag dumura nang malakas, magmumog, gumamit ng straw o manigarilyo; "
           "kumain ng malambot at malamig na pagkain at ngumuya sa kabilang side; makakatulong ang cold compress sa pamamaga. "
           "Tumawag po sa branch kung hindi tumitigil ang dugo, o lumala ang sakit o pamamaga pagkalipas ng 2 hanggang 3 araw."},
    {"key": "wisdom", "service": "oral-surgery",
     "kw": ["wisdom", "impacted", "odontectomy", "bagang sa dulo", "huling bagang", "tumutubong bagang"],
     "en": "Wisdom teeth don't always need to be removed. Your dentist checks them with an X-ray (panoramic or 3D CBCT) to see their position. "
           "Removal is usually recommended if the tooth is impacted, keeps getting infected, causes pain, or damages the tooth next to it.",
     "tl": "Hindi po laging kailangang tanggalin ang wisdom tooth. Titingnan ito ng dentista gamit ang X-ray (panoramic o 3D CBCT) para makita ang posisyon. "
           "Karaniwang inirerekomendang tanggalin kung impacted, paulit-ulit na namamaga, masakit, o nasisira ang katabing ngipin."},
    {"key": "root_canal", "service": "restorative-dentistry",
     "kw": ["root canal", "rct", "patay na ugat", "nerve treatment", "infected tooth", "abscess"],
     "en": "A root canal saves a badly decayed or infected tooth instead of pulling it. The infected pulp inside is cleaned out, and the tooth is sealed. "
           "It's done with local anesthesia, and a crown is often recommended afterwards to protect the tooth.",
     "tl": "Ang root canal ay paraan para mailigtas ang ngiping sirang-sira o may impeksyon sa halip na bunutin. Nililinis ang loob ng ngipin at sinasara. "
           "Ginagawa ito nang may anesthesia, at madalas inirerekomenda ang crown pagkatapos para maprotektahan ang ngipin."},
    {"key": "whitening", "service": "aesthetic-dentistry", "guide": "veneers-vs-crowns",
     "kw": ["whitening", "pampaputi", "paputi", "yellow teeth", "madilaw", "dilaw na ngipin", "stain", "mantsa sa ngipin", "bleaching"],
     "en": "Professional whitening brightens natural teeth by several shades. Results vary from person to person, and some people feel temporary sensitivity for a day or two. "
           "Whitening doesn't change the color of crowns, veneers or fillings, so your dentist will check your teeth first.",
     "tl": "Ang professional whitening ay nagpapaputi ng natural na ngipin nang ilang shade. Iba-iba ang resulta, at may ilang nakakaramdam ng pansamantalang sensitivity nang isa o dalawang araw. "
           "Hindi nagbabago ng kulay ang crowns, veneers o pasta, kaya titingnan muna ng dentista ang inyong ngipin."},
    {"key": "braces_long", "service": "orthodontics", "guide": "braces-or-clear-aligners",
     "kw": ["how long braces", "braces take", "long braces", "tagal braces", "gaano katagal braces", "gaano katagal ang braces", "how long will i wear", "ilang taon braces", "braces duration", "adjustment"],
     "en": "Treatment with braces usually takes about 1 to 3 years, depending on how much the teeth need to move. You'll come back regularly, usually every month, for adjustments. "
           "After braces, wearing a retainer keeps your teeth in place.",
     "tl": "Karaniwang 1 hanggang 3 taon po ang braces, depende sa kung gaano kalaki ang kailangang galaw ng ngipin. Babalik kayo nang regular, kadalasan buwan-buwan, para sa adjustment. "
           "Pagkatapos ng braces, ang retainer ang magpapanatili sa ayos ng ngipin."},
    {"key": "missing_tooth", "service": "prosthodontics", "guide": "dental-implants-what-to-expect",
     "kw": ["missing tooth", "nawalang ngipin", "walang ngipin", "bungi", "replace tooth", "palitan ang ngipin", "denture or implant", "implant or denture",
            "implant vs", "tooth gap", "nabunot na ngipin"],
     "en": "There are three main ways to replace a missing tooth: a dental implant (fixed, doesn't touch the neighboring teeth), a bridge (fixed, supported by the teeth beside the gap), "
           "or a denture (removable, and usually the most affordable). Your dentist will check your teeth and bone and explain which fits you best.",
     "tl": "May tatlong pangunahing paraan para palitan ang nawalang ngipin: dental implant (nakakabit, hindi ginagalaw ang katabing ngipin), bridge (nakakabit, nakakapit sa katabing ngipin), "
           "o pustiso (natatanggal, at kadalasang pinaka-abot-kaya). Titingnan ng dentista ang inyong ngipin at buto at ipapaliwanag kung alin ang bagay sa inyo."},
    {"key": "implant_long", "service": "prosthodontics", "guide": "dental-implants-what-to-expect",
     "kw": ["how long implant", "gaano katagal implant", "implant process", "implant takes", "implant healing"],
     "en": "An implant is usually done in stages over a few months: planning with a 3D scan, placing the implant, a few months of healing while it bonds with the bone, then the final crown. "
           "Your dentist will give you a timeline for your case.",
     "tl": "Karaniwang ilang buwan po ang implant, sa ilang yugto: planning gamit ang 3D scan, paglalagay ng implant, ilang buwang paghilom habang kumakapit sa buto, at ang huling crown. "
           "Bibigyan kayo ng dentista ng timeline para sa inyong kaso."},
    {"key": "bleeding_gums", "service": "periodontal-care",
     "kw": ["bleeding gums", "gums bleed", "gums are bleeding", "gums bleeding", "bleeding when i brush", "dumudugo ang gilagid", "gums", "dumudugo gilagid", "dumudugong gilagid", "nagdudugo ang gilagid", "gum bleeding", "swollen gums", "gilagid"],
     "en": "Gums that bleed when you brush are often a sign of gum inflammation (gingivitis), usually from plaque and tartar. A professional cleaning and good daily brushing and flossing often help. "
           "It's best to have it checked, because untreated gum disease can get worse.",
     "tl": "Ang pagdurugo ng gilagid habang nagsisipilyo ay kadalasang senyales ng pamamaga ng gilagid (gingivitis), dahil sa plaque at tartar. Nakakatulong ang professional cleaning at maayos na pagsisipilyo at floss araw-araw. "
           "Mas mabuti pong ipa-check, dahil puwedeng lumala ang sakit sa gilagid kapag hindi naagapan."},
    {"key": "receding", "service": "periodontal-care",
     "kw": ["receding gums", "receding gum", "gum recession", "umuurong na gilagid", "umuurong ang gilagid", "exposed root", "long teeth", "gum graft"],
     "en": "Receding gums expose the roots of the teeth, which can cause sensitivity and make teeth look longer. Common causes are gum disease and brushing too hard. "
           "Depending on the cause, treatment may include a deep cleaning (scaling and root planing) or gum grafting to cover and protect the exposed roots.",
     "tl": "Kapag umuurong ang gilagid, lumalabas ang ugat ng ngipin, kaya puwedeng mangilo at magmukhang mas mahaba ang ngipin. Karaniwang dahilan ang sakit sa gilagid at sobrang diin ng pagsisipilyo. "
           "Depende sa dahilan, puwedeng irekomenda ang deep cleaning (scaling and root planing) o gum grafting para matakpan at maprotektahan ang ugat."},
    {"key": "bad_breath", "service": "general-dentistry",
     "kw": ["bad breath", "mabaho hininga", "mabahong hininga", "halitosis", "bad smell mouth"],
     "en": "Bad breath is commonly caused by plaque, tartar, gum problems, cavities or a coated tongue. Brushing twice a day, cleaning your tongue, flossing, and a professional cleaning usually help. "
           "If it continues, your dentist can check for the cause.",
     "tl": "Karaniwang dahilan ng mabahong hininga ang plaque, tartar, problema sa gilagid, butas na ngipin o maruming dila. Nakakatulong ang pagsisipilyo nang dalawang beses sa isang araw, paglilinis ng dila, floss, at professional cleaning. "
           "Kung hindi nawawala, matitingnan ng dentista ang dahilan."},
    {"key": "sensitive", "service": "general-dentistry",
     "kw": ["sensitive", "sensitivity", "ngilo", "nangingilo", "ngumingilo", "cold drinks hurt", "malamig masakit"],
     "en": "Sensitive teeth can come from worn enamel, receding gums, a cavity, or a cracked filling. A toothpaste for sensitive teeth often helps, "
           "but it's good to have a check-up so the dentist can find and treat the cause.",
     "tl": "Ang pangingilo ay puwedeng dahil sa nasirang enamel, umuurong na gilagid, butas na ngipin, o sirang pasta. Nakakatulong ang toothpaste para sa sensitive teeth, "
           "pero mas mabuting magpa-check-up para malaman at magamot ng dentista ang dahilan."},
    {"key": "broken", "service": "restorative-dentistry", "guide": "veneers-vs-crowns",
     "kw": ["broken tooth", "chipped", "cracked", "nabasag", "nabiyak", "natapyas", "sira ang ngipin", "basag na ngipin", "chip"],
     "en": "If a tooth breaks or chips, rinse your mouth with warm water, keep any pieces, and call the nearest branch as soon as you can. "
           "Small chips can often be repaired with tooth-colored bonding; bigger breaks may need a crown.",
     "tl": "Kung nabasag o natapyas ang ngipin, magmumog ng maligamgam na tubig, itabi ang piraso kung mayroon, at tumawag agad sa pinakamalapit na branch. "
           "Ang maliit na tapyas ay kadalasang naaayos ng tooth-colored bonding; ang malaking sira ay puwedeng kailanganin ng crown."},
    {"key": "lost_filling", "service": "restorative-dentistry", "guide": "about-dental-fillings",
     "kw": ["natanggal pasta", "filling fell", "natanggal pasta", "natanggal ang pasta", "lost filling", "crown fell", "natanggal crown", "jacket natanggal", "natanggal ang jacket", "loose crown"],
     "en": "If a filling or crown comes off, keep the crown if you have it, avoid chewing on that side, and call the branch to have it checked and fixed soon.",
     "tl": "Kung natanggal ang pasta o crown, itabi po ang crown kung mayroon, iwasang ngumuya sa side na iyon, at tumawag sa branch para maipa-check at maayos agad."},
    {"key": "pregnant", "service": "general-dentistry",
     "kw": ["pregnant", "am pregnant", "im pregnant", "while pregnant", "during pregnancy", "buntis ako", "buntis po ako", "buntis", "pregnancy", "nagbubuntis", "breastfeeding", "nagpapasuso"],
     "en": "Dental check-ups and cleanings are safe and important during pregnancy, because pregnancy can make gums more prone to swelling and bleeding. "
           "Just tell your dentist you're pregnant and how many weeks. They'll plan your care accordingly, and X-rays are taken only if really needed.",
     "tl": "Ligtas at mahalaga po ang check-up at cleaning habang buntis, dahil mas madaling mamaga at dumugo ang gilagid sa pagbubuntis. "
           "Sabihin lang po sa dentista na buntis kayo at ilang linggo na. Iaangkop nila ang treatment, at magpapa-X-ray lang kung talagang kailangan."},
    {"key": "grinding", "service": "orthodontics",
     "kw": ["grinding", "bruxism", "nagngangalit", "nagngangalit ng ngipin", "clenching", "night guard", "mouthguard", "mouth guard", "sports guard", "gigil"],
     "en": "Teeth grinding or clenching, often at night, can wear down teeth and cause jaw pain or headaches. A custom night guard can protect your teeth, "
           "and your dentist can check your bite and jaw joint (TMJ).",
     "tl": "Ang paggigiling o pagngangalit ng ngipin, kadalasan sa gabi, ay puwedeng makasira ng ngipin at magdulot ng sakit sa panga o ulo. Makakatulong ang custom night guard, "
           "at matitingnan ng dentista ang inyong kagat at panga (TMJ). Gumagawa rin kami ng pasadyang mouthguard para sa contact sports."},
    {"key": "crooked", "service": "orthodontics", "guide": "braces-or-clear-aligners",
     "kw": ["crooked", "sungki", "gap teeth", "gaps", "may siwang", "siwang", "uneven teeth", "overbite", "underbite", "tabingi", "sumasalungat"],
     "en": "Crooked teeth and gaps can be straightened with braces or clear aligners. For small gaps or uneven edges, veneers or bonding can also improve the look. "
           "Your dentist will check your bite and show you the options.",
     "tl": "Ang sungki at may siwang na ngipin ay naaayos ng braces o clear aligners. Para sa maliit na siwang o hindi pantay na gilid, puwede rin ang veneers o bonding. "
           "Titingnan ng dentista ang inyong kagat at ipapakita ang mga opsyon."},
    {"key": "walk_in", "service": "",
     "kw": ["walk in", "walk-in", "walkin", "need appointment", "need an appointment", "need to book", "kailangan ba mag-book", "kailangan ba ng appointment", "pwede pumunta", "puwede pumunta", "diretso na lang", "same day"],
     "en": "We recommend booking ahead so a dentist and chair are ready for you. For a same-day visit, please call the branch first to check availability.",
     "tl": "Mas mainam pong mag-book muna para nakahanda ang dentista at upuan para sa inyo. Para sa same-day na pagpunta, tumawag po muna sa branch para malaman kung may bakante."},
    {"key": "change_booking", "service": "",
     "kw": ["reschedule", "cancel", "cancellation", "cancellation fee", "missed my appointment", "missed appointment", "rebook", "move my appointment", "change my appointment", "i-cancel", "ipa-cancel", "ilipat ang schedule", "palitan ang schedule", "resched"],
     "en": "To reschedule or cancel, please call or text your branch as early as you can, and our team will find you a new time. If you missed an appointment, just book a new one online or call the branch. For any cancellation policy, the branch will give you the details.",
     "tl": "Para mag-reschedule o mag-cancel, tumawag o mag-text po sa inyong branch sa lalong madaling panahon, at hahanapan kayo ng bagong oras ng aming team. Kung hindi kayo nakapunta sa appointment, mag-book lang ulit online o tumawag sa branch. Para sa anumang cancellation policy, ibibigay po ng branch ang detalye."},
    {"key": "bring", "service": "",
     "kw": ["bring", "arrive early", "come early", "agahan", "maaga", "what to bring", "ano dadalhin", "anong dadalhin", "ano ang dadalhin", "requirements", "first appointment", "unang punta", "prepare for"],
     "en": "For your visit, bring a list of any medicines you take and let us know about allergies or health conditions. If you have recent dental X-rays, bring them too. "
           "Please arrive about 10 minutes early.",
     "tl": "Sa inyong pagbisita, dalhin po ang listahan ng mga gamot na iniinom ninyo at sabihin kung may allergy o karamdaman. Kung may bagong dental X-ray, dalhin din po. "
           "Pumunta nang mga 10 minuto bago ang oras."},
    {"key": "discount", "service": "",
     "kw": ["senior", "pwd", "discount", "promo", "sale", "libre", "free consultation", "philhealth", "hmo", "insurance", "maxicare", "intellicare",
            "gcash", "maya", "credit card", "osca", "payment", "bayad"],
     "en": "For discounts, HMO, and payment options such as cards, e-wallets or installment plans, the branch will give you the exact details. Want our team to get in touch?",
     "tl": "Para sa discount, HMO, at paraan ng pagbabayad gaya ng card, e-wallet o hulugan, ang branch po ang magbibigay ng eksaktong detalye. Gusto n'yo po bang tawagan kayo ng aming team?"},
    {"key": "sedation", "service": "pediatric-dentistry", "guide": "childs-first-dental-visit",
     "kw": ["sedation", "sedate", "pampatulog", "tulog habang", "special needs", "autism", "autistic", "pwd patient"],
     "en": "We provide gentle care for children and patients with special needs, including conscious sedation when appropriate. "
           "Your dentist will assess the patient first and explain what's safest and most comfortable.",
     "tl": "Maingat po ang aming pag-aalaga sa mga bata at pasyenteng may special needs, kasama ang conscious sedation kung angkop. "
           "Titingnan muna ng dentista ang pasyente at ipapaliwanag kung ano ang pinakaligtas at komportable."},
    {"key": "kids_age", "service": "pediatric-dentistry",
     "guide": "childs-first-dental-visit",
     "kw": ["year old", "years old", "when should we visit", "when to bring", "first visit", "what age", "anong edad", "ilang taon dapat", "baby teeth", "first tooth", "unang ngipin", "toddler", "sanggol", "gatas na ngipin", "baby ko"],
     "en": "Bring your child for their first dental visit by their first birthday, or within 6 months of the first tooth. Baby teeth matter: they help your child eat, speak, and hold space for adult teeth.",
     "tl": "Dalhin po ang bata sa unang dental visit bago mag-isang taon, o sa loob ng 6 na buwan mula nang tumubo ang unang ngipin. Mahalaga ang gatas na ngipin: tumutulong ito sa pagkain, pagsasalita, at naglalaan ng puwang para sa permanenteng ngipin."},
    {"key": "denture_care", "service": "prosthodontics", "guide": "caring-for-dentures",
     "kw": ["denture", "pustiso", "dentures", "flexite", "false teeth"],
     "en": "We make complete and partial dentures, fitted in our own digital lab. New dentures take a few weeks to get used to, and we adjust them for comfort. "
           "Clean them daily and soak them overnight so they don't dry out.",
     "tl": "Gumagawa po kami ng complete at partial na pustiso, sa sarili naming digital lab. Ilang linggo ang pag-aadjust sa bagong pustiso, at inaayos namin ito para komportable. "
           "Linisin araw-araw at ibabad sa gabi para hindi matuyo."},
    {"key": "xray_safe", "service": "general-dentistry",
     "kw": ["x-ray safe", "xray safe", "radiation", "ligtas ba ang x-ray", "safe ba ang xray", "cbct safe"],
     "en": "Dental X-rays use a low dose of radiation, and they're taken only when they help your dentist diagnose or plan treatment. Let us know if you're pregnant.",
     "tl": "Mababa po ang radiation ng dental X-ray, at ginagawa lang ito kapag makakatulong sa diagnosis o plano ng treatment. Sabihin po kung kayo ay buntis."},
    {"key": "brushing", "service": "general-dentistry",
     "kw": ["how to brush", "paano magsipilyo", "toothpaste", "toothbrush", "sipilyo", "floss", "mouthwash"],
     "en": "Brush twice a day for 2 minutes with a fluoride toothpaste and a soft brush, clean between your teeth daily with floss, and limit sugary snacks and drinks. "
           "Regular check-ups catch small problems early.",
     "tl": "Magsipilyo nang dalawang beses sa isang araw, 2 minuto, gamit ang fluoride toothpaste at malambot na sipilyo; mag-floss araw-araw; at bawasan ang matatamis. "
           "Ang regular na check-up ay nakakahuli ng maliliit na problema bago lumala."},
    {"key": "emergency_offer", "service": "",
     "kw": ["emergency dental", "dental emergency", "emergency procedure", "emergency appointment", "same day emergency", "emergency ba", "urgent appointment"],
     "en": "For a dental emergency such as severe pain, a broken or knocked-out tooth, or swelling, call your nearest branch right away so we can try to see you as soon as possible during clinic hours (Monday to Saturday, 9 AM to 6 PM). "
           "For severe facial swelling, trouble breathing or swallowing, or bleeding that won't stop, go to the nearest hospital emergency room or call 911.",
     "tl": "Para sa dental emergency gaya ng matinding sakit, nabasag o natanggal na ngipin, o pamamaga, tumawag agad sa pinakamalapit na branch para masubukan namin kayong makita sa lalong madaling panahon sa oras ng clinic (Lunes hanggang Sabado, 9 AM hanggang 6 PM). "
           "Kung matindi ang pamamaga ng mukha, hirap huminga o lumunok, o hindi tumitigil ang dugo, pumunta sa pinakamalapit na emergency room o tumawag sa 911."},
    {"key": "knocked_out", "service": "",
     "kw": ["knocked out", "knocked-out", "tooth fell out", "natanggal ang ngipin", "nalaglag ang ngipin", "natanggal na ngipin", "tumalsik ang ngipin"],
     "en": "If a permanent tooth is knocked out: hold it by the crown (not the root), rinse it gently if dirty, and keep it moist in milk or saliva. Call the nearest branch right away: the sooner a dentist sees it, ideally within an hour, the better the chance of saving it.",
     "tl": "Kung natanggal ang permanenteng ngipin: hawakan sa korona (hindi sa ugat), banlawan nang marahan kung marumi, at panatilihing basa sa gatas o laway. Tumawag agad sa pinakamalapit na branch: mas maaga itong makita ng dentista, mas mabuti kung sa loob ng isang oras, mas malaki ang tsansang mailigtas."},
    {"key": "medication", "service": "",
     "kw": ["medicine", "medication", "gamot", "painkiller", "pain killer", "pain reliever", "mefenamic", "ibuprofen", "paracetamol", "biogesic", "antibiotic",
            "amoxicillin", "anong iinumin", "what can i take", "recommend something"],
     "en": "I'm not able to recommend or prescribe medicine in this chat, because the right choice depends on your health, allergies and other medicines. Please call your branch so a dentist can advise you. "
           "If the pain is severe, or you have swelling or a fever, see a dentist as soon as possible, or go to the emergency room if it's serious.",
     "tl": "Hindi po ako makapagrerekomenda o makapagreseta ng gamot dito, dahil depende ito sa inyong kalusugan, allergy at iba pang iniinom na gamot. Pakitawagan ang branch para mapayuhan kayo ng dentista. "
           "Kung matindi ang sakit, o may pamamaga o lagnat, magpatingin agad sa dentista, o pumunta sa emergency room kung malala."},
    {"key": "toothache_cause", "service": "general-dentistry",
     "kw": ["what's causing", "whats causing", "what is causing", "cause of my", "why does my tooth", "why is my tooth", "bakit sumasakit", "bakit masakit", "ano ang dahilan"],
     "en": "I can't tell what's causing it from a chat, but common causes of toothache include a cavity, a cracked tooth or filling, gum problems, an infection, or sensitive teeth. "
           "A dentist can find the cause with a quick exam and, if needed, an X-ray. Would you like to book a check-up?",
     "tl": "Hindi ko po masasabi ang dahilan sa chat, pero karaniwang sanhi ng sakit ng ngipin ang butas, bitak na ngipin o pasta, problema sa gilagid, impeksyon, o sensitive na ngipin. "
           "Malalaman ng dentista ang dahilan sa mabilis na pagsusuri at X-ray kung kailangan. Gusto n'yo po bang mag-book ng check-up?"},
    {"key": "which_right", "service": "",
     "kw": ["which procedure", "which treatment", "right for me", "best for me", "what do i need", "ano ang kailangan ko", "anong treatment", "bagay sa akin", "best option"],
     "en": "The best way to know is a consultation: your dentist checks your teeth, takes X-rays if needed, and explains your options, timelines and costs so you can choose what's right for you.",
     "tl": "Ang pinakamainam na paraan ay magpakonsulta: titingnan ng dentista ang inyong ngipin, kukuha ng X-ray kung kailangan, at ipapaliwanag ang mga opsyon, tagal at halaga para makapili kayo ng tama para sa inyo."},
    {"key": "languages", "service": "",
     "kw": ["language", "languages", "speak english", "speak tagalog", "what languages", "anong wika", "marunong ba mag-english", "nagsasalita"],
     "en": "This chat works in English and Tagalog: switch anytime with EN / TL at the top. For help in another language, please call your branch.",
     "tl": "Gumagana ang chat na ito sa English at Tagalog: puwedeng magpalit anumang oras gamit ang EN / TL sa itaas. Para sa ibang wika, pakitawagan ang branch."},
    {"key": "accessible", "service": "",
     "kw": ["wheelchair", "accessible", "accessibility", "disability", "disabled", "ramp", "elevator", "stairs", "hagdan", "naka-wheelchair"],
     "en": "Please call your branch before your visit so they can tell you about access at that location and prepare to assist you.",
     "tl": "Pakitawagan po ang branch bago pumunta para masabi nila ang tungkol sa pagpasok sa lugar na iyon at makapaghanda silang tumulong."},
    {"key": "companion", "service": "",
     "kw": ["bring someone", "bring a companion", "bring my", "companion", "kasama", "may kasama", "isama", "can my mom", "can my husband", "can my wife", "can my friend"],
     "en": "You're welcome to bring someone with you for support. Children should come with a parent or guardian.",
     "tl": "Puwede po kayong magsama ng kasama para sa suporta. Ang mga bata ay dapat may kasamang magulang o guardian."},
    {"key": "eat_before", "service": "",
     "kw": ["eat before", "kumain bago", "breakfast before", "before my appointment", "brush before", "brush my teeth before", "magsipilyo bago", "fast before", "ayuno"],
     "en": "For most treatments, yes: eat a light meal and brush your teeth before you come. If you're having sedation or certain surgeries, your dentist may ask you not to eat beforehand, so follow any instructions you're given.",
     "tl": "Sa karamihan ng treatment, opo: kumain nang magaan at magsipilyo bago pumunta. Kung may sedation o ilang surgery, puwedeng sabihan kayong huwag kumain bago nito, kaya sundin ang ibibigay na bilin."},
    {"key": "appointment_length", "service": "",
     "kw": ["how long will my appointment", "how long is my appointment", "how long is the appointment", "how long will the appointment", "gaano katagal ang appointment", "how long will i be there"],
     "en": "It depends on the treatment: a check-up and cleaning usually takes about 30 to 60 minutes, a filling 20 to 60 minutes, and longer treatments like root canals or surgery 1 to 2 hours. Tell me which treatment and I'll give you a closer estimate.",
     "tl": "Depende po sa treatment: karaniwang 30 hanggang 60 minuto ang check-up at cleaning, 20 hanggang 60 minuto ang pasta, at 1 hanggang 2 oras ang mas mahabang treatment gaya ng root canal o surgery. Sabihin kung anong treatment para mas eksakto ang sagot ko."},
    {"key": "book_here", "service": "",
     "kw": ["book through this chat", "book through the chat", "book here", "book in this chat", "book via chat", "dito na lang mag-book", "dito mag-book", "pwede ba dito"],
     "en": "Yes! Tap \"Book a visit\" and I'll take you straight to our booking page with your branch and treatment already filled in: just pick a time. Or tap \"Have our team call me\" and we'll call you to set it up.",
     "tl": "Opo! I-tap ang \"Mag-book\" at dadalhin ko kayo sa booking page na nakalagay na ang branch at treatment: pumili na lang ng oras. O i-tap ang \"Patawagan ako sa staff\" at tatawagan namin kayo."},
    {"key": "website", "service": "",
     "kw": ["website", "web site", "webpage", "online site"],
     "en": "You're on it: this is Dental Haven's website. Each branch also has its own Facebook page, which I can show you under Branches.",
     "tl": "Nandito na po kayo: ito ang website ng Dental Haven. May sariling Facebook page din ang bawat branch, na maipapakita ko sa Branches."},
    {"key": "parking", "service": "",
     "kw": ["parking", "park my car", "paradahan", "may parking", "saan mag-park", "saan magpark"],
     "en": "For parking at a specific branch, please call that branch; they'll tell you the nearest parking spot. I can also show you each branch's map.",
     "tl": "Para sa parking sa isang branch, pakitawagan po ang branch na iyon; sasabihin nila ang pinakamalapit na paradahan. Maipapakita ko rin ang mapa ng bawat branch."},
    {"key": "dont_see", "service": "",
     "kw": ["haven't asked", "havent asked", "don't see", "dont see", "not here", "other question", "another question", "ibang tanong", "wala dito", "may tanong pa ako"],
     "en": "No problem: our team can answer anything I can't. Leave your name and number and we'll get back to you, or call your nearest branch.",
     "tl": "Walang problema: masasagot ng aming team ang hindi ko kaya. Iwan ang pangalan at numero at babalikan namin kayo, o tumawag sa pinakamalapit na branch."},
    {"key": "materials_safe", "service": "",
     "kw": ["materials safe", "material safe", "safe materials", "materials you use safe", "ligtas ba ang materyales", "biocompatible", "mercury", "toxic"],
     "en": "Dental materials are made specifically for use in the mouth and are widely used and tested. Your dentist chooses materials that suit your health, and will discuss any concerns, including allergies or a preference for metal-free options.",
     "tl": "Ang dental materials ay ginawa para sa bibig at malawakang ginagamit at sinusuri. Pumipili ang dentista ng materyales na angkop sa inyong kalusugan, at pag-uusapan ang anumang alalahanin, kasama ang allergy o kagustuhan sa walang-metal na opsyon."},
    {"key": "allergy", "service": "",
     "kw": ["allergy", "allergies", "allergic", "allergic to metal", "nickel", "latex", "may allergy", "about any allergies", "any allergies", "allergies before", "tell you about my allergies"],
     "en": "Yes, please tell your dentist about any allergies before treatment, for example to metals like nickel, latex, anesthetics, or medicines. There are alternative materials for many treatments, such as metal-free crowns and ceramic braces.",
     "tl": "Opo, sabihin po sa dentista ang anumang allergy bago ang treatment, halimbawa sa metal gaya ng nickel, latex, anesthesia, o gamot. May alternatibong materyales para sa maraming treatment, gaya ng metal-free na crown at ceramic braces."},
    {"key": "choose_material", "service": "",
     "kw": ["choose the material", "choose my material", "pick the material", "pumili ng materyales", "pumili ng material", "can i choose", "material options"],
     "en": "Yes. When there's more than one suitable option, your dentist explains each one (how it looks, how long it lasts, and the cost) so you can choose what fits your needs and budget.",
     "tl": "Opo. Kapag may higit sa isang angkop na opsyon, ipapaliwanag ng dentista ang bawat isa (itsura, tibay at halaga) para mapili ninyo ang bagay sa inyong pangangailangan at budget."},
    {"key": "material_cost", "service": "",
     "kw": ["material affect the cost", "materials affect the cost", "material affect the price", "depends on the material", "depende sa materyales", "mas mahal ba", "cost depend on material"],
     "en": "Yes, the material affects the cost. For example, zirconia or porcelain crowns usually cost more than metal ones, and porcelain veneers more than composite. Your dentist will give you the price for each option before treatment.",
     "tl": "Opo, nakakaapekto ang materyales sa halaga. Halimbawa, mas mahal kadalasan ang zirconia o porcelain na crown kaysa metal, at ang porcelain veneers kaysa composite. Ibibigay ng dentista ang presyo ng bawat opsyon bago ang treatment."},
    {"key": "samples", "service": "",
     "kw": ["samples", "sample of the material", "show me the material", "show me samples", "see the materials", "makita ang materyales", "ipakita"],
     "en": "At your consultation you can ask your dentist to show you the options for your treatment, such as shade guides for tooth-colored materials, and explain how each one looks.",
     "tl": "Sa konsulta, puwede ninyong hilingin sa dentista na ipakita ang mga opsyon para sa inyong treatment, gaya ng shade guide para sa tooth-colored na materyales, at ipaliwanag ang itsura ng bawat isa."},
    {"key": "material_diff", "service": "",
     "kw": ["differences between the", "difference between the materials", "which material is better", "best material", "materials last", "each material", "anong materyales ang mas maganda"],
     "en": "Each material has trade-offs: tooth-colored options (composite, ceramic, zirconia, porcelain) look the most natural; metal options are very strong and often cost less; porcelain and zirconia usually last longest. Tell me the treatment (for example crowns, fillings or veneers) and I'll explain its options.",
     "tl": "May kanya-kanyang kalamangan ang bawat materyales: ang tooth-colored (composite, ceramic, zirconia, porcelain) ang pinaka-natural ang itsura; ang metal ay napakatibay at kadalasang mas mura; ang porcelain at zirconia ang karaniwang pinakamatagal. Sabihin ang treatment (hal. crown, pasta o veneers) at ipapaliwanag ko ang mga opsyon."},
    {"key": "temporary", "service": "restorative-dentistry",
     "kw": ["temporary crown", "temporary crowns", "temporary filling", "temporary fillings", "temporary", "pansamantalang"],
     "en": "Temporary crowns are usually made of acrylic or composite, and temporary fillings of a soft temporary filling material. They protect the tooth for a short time until the final crown or filling is ready, so avoid sticky and hard food on that side.",
     "tl": "Ang temporary crown ay kadalasang gawa sa acrylic o composite, at ang temporary na pasta ay sa malambot na pansamantalang materyales. Pinoprotektahan nito ang ngipin habang hinihintay ang final na crown o pasta, kaya iwasan ang malagkit at matigas na pagkain sa side na iyon."},
    {"key": "book_channels", "service": "",
     "kw": ["whatsapp", "viber", "dm", "via dm", "through dm", "messenger", "facebook message", "message you on facebook", "sa messenger", "sa fb", "via fb", "through facebook"],
     "en": "The quickest way is to book online right here: choose your branch, service and preferred time, and the branch will confirm with you. You can also call your branch or message its Facebook page. For other messaging apps, please check with your branch.",
     "tl": "Pinakamabilis po ang mag-book online dito mismo: piliin ang branch, serbisyo at gustong oras, at kokontakin kayo ng branch para kumpirmahin. Puwede rin pong tumawag sa branch o mag-message sa Facebook page nito. Para sa ibang messaging app, pakitanong po sa inyong branch."},
    {"key": "waitlist", "service": "",
     "kw": ["waitlist", "wait list", "waiting list", "earlier slot", "earlier schedule", "earlier time", "mas maagang schedule", "cancellation list", "slot opens"],
     "en": "We don't have an automatic waitlist on the website yet. Book the best available time now, then ask your branch to let you know if an earlier slot opens up; they'll move you if they can.",
     "tl": "Wala pa po kaming automatic waitlist sa website. Mag-book po muna ng pinakamagandang bakanteng oras, tapos hilingin sa branch na sabihan kayo kung may mas maagang bakante; ililipat nila kayo kung kaya."},
    {"key": "book_ahead", "service": "general-dentistry",
     "kw": ["how far in advance", "how early should i book", "how early should i schedule", "advance booking", "book in advance", "book ahead", "ilang araw bago", "gaano kaaga mag-book", "gaano kaaga magpa-book"],
     "en": "For a routine cleaning or check-up, booking a few days to a week ahead usually gives you the widest choice of times, and you can see the open times when you book online. For pain or an urgent problem, call your branch the same day.",
     "tl": "Para sa regular na cleaning o check-up, ang pag-book nang ilang araw hanggang isang linggo bago ang gusto ninyong araw ang kadalasang may pinakamaraming mapagpipiliang oras, at makikita ninyo ang bakanteng oras kapag nag-book online. Kung may sakit o urgent na problema, tumawag po sa branch sa mismong araw."},
    {"key": "intake_forms", "service": "",
     "kw": ["intake form", "intake forms", "forms online", "fill out forms", "fill out online", "fill up forms", "fill-up form", "patient form", "patient forms", "medical history form", "registration form", "digital forms"],
     "en": "When you book online, you already give us your basic details. Your medical and dental history is taken at the clinic before your first treatment, so please arrive about 10 minutes early and bring a list of the medicines you take.",
     "tl": "Kapag nag-book kayo online, naibigay na po ninyo ang inyong basic na detalye. Ang inyong medical at dental history ay kukunin sa clinic bago ang unang treatment, kaya dumating po nang mga 10 minuto nang maaga at dalhin ang listahan ng mga gamot na iniinom ninyo."},
    {"key": "insurance_check", "service": "",
     "kw": ["insurance coverage", "check my insurance", "check my coverage", "cover cosmetic", "insurance cover", "insurance covers", "hmo cover", "hmo covers", "covered by my hmo", "covered by insurance", "sagot ng hmo", "covered ba", "cashless", "direct billing", "reimbursement", "pay upfront"],
     "en": "Coverage depends on your HMO or insurance plan. Many plans cover basic care like check-ups, cleanings, simple fillings and extractions, while cosmetic treatments such as veneers and whitening are often not covered. Please check your plan with your provider, and ask your branch which HMOs they accept, whether they can verify your coverage before treatment, and how billing works.",
     "tl": "Depende po sa inyong HMO o insurance plan ang coverage. Maraming plan ang sumasagot sa basic na serbisyo gaya ng check-up, cleaning, simpleng pasta at bunot, pero ang cosmetic gaya ng veneers at whitening ay kadalasang hindi sakop. Pakitanong po sa inyong provider, at itanong sa branch kung aling HMO ang tinatanggap nila, kung puwede nilang i-check ang coverage bago ang treatment, at paano ang bayaran."},
    {"key": "price_vary", "service": "",
     "kw": ["prices vary", "price vary", "prices differ", "different prices", "why do prices", "why is the price different", "why the range", "price range", "bakit iba-iba ang presyo", "bakit magkaiba ang presyo"],
     "en": "The final cost depends on each patient's case: how many teeth are involved, how much work each tooth needs (for example a standard or a difficult root canal), the material you choose (such as zirconia, E.max or composite), and whether extra steps like X-rays, a build-up or a temporary crown are needed. That's why we give ranges or \"from\" prices. Your dentist confirms the exact cost at your consultation, before any work begins.",
     "tl": "Depende po sa kaso ng bawat pasyente ang huling halaga: ilang ngipin ang gagawin, gaano kalaki ang trabaho sa bawat ngipin (halimbawa standard o mahirap na root canal), ang materyales na pipiliin (gaya ng zirconia, E.max o composite), at kung kailangan ng dagdag na hakbang gaya ng X-ray, build-up o temporary crown. Kaya range o \"mula\" na presyo ang ibinibigay namin. Kukumpirmahin ng dentista ang eksaktong halaga sa konsulta, bago simulan ang anumang treatment."},
    {"key": "installment", "service": "",
     "kw": ["installment", "installments", "hulugan", "monthly payment", "monthly payments", "down payment", "downpayment", "financing", "zero interest", "0% interest", "in-house financing", "payment plan", "payment plans", "payment scheme"],
     "en": "For braces, we offer payment packages with a downpayment and monthly payments. For other treatments and for credit card installment promos, your branch will tell you the options available.",
     "tl": "Para sa braces, may payment package po kami na may downpayment at buwanang hulog. Para sa ibang treatment at sa credit card installment promo, sasabihin po ng branch ang mga opsyon."},
    {"key": "seniors", "service": "",
     "kw": ["older adults", "older adult", "elderly", "geriatric", "senior citizens", "seniors", "matatanda", "lolo", "lola", "dental care for older"],
     "en": "Yes, we care for older adults every day: check-ups and cleanings, gum care, fillings and root canals, dentures (complete and partial), implants and more. Please tell your dentist about your medical conditions and bring a list of your medicines, especially blood thinners or medicines for diabetes, blood pressure or the heart. For senior citizen discounts, your branch will give you the details.",
     "tl": "Opo, araw-araw po kaming nag-aalaga ng mga nakatatanda: check-up at cleaning, gum care, pasta at root canal, pustiso (buo at partial), implant at iba pa. Pakisabi po sa dentista ang inyong mga karamdaman at dalhin ang listahan ng inyong gamot, lalo na ang pampalabnaw ng dugo o gamot sa diabetes, altapresyon o puso. Para sa senior citizen discount, ibibigay po ng branch ang detalye."},
    {"key": "rct_signs", "service": "restorative-dentistry",
     "kw": ["filling or a root canal", "filling or root canal", "need a root canal", "root canal symptoms", "signs i need", "signs that i need", "kailangan ba ng root canal", "pasta o root canal"],
     "en": "Your dentist confirms it with an exam and an X-ray, but here's a guide. A small cavity with little or no pain usually needs just a filling. A root canal is more likely if you have strong or lingering pain with hot or cold, a throbbing toothache (especially at night), pain when biting, swelling or a pimple on the gum near the tooth, or a tooth that has turned darker. Treating a cavity early often avoids a root canal.",
     "tl": "Kukumpirmahin ito ng dentista sa pagsusuri at X-ray, pero narito ang gabay. Ang maliit na butas na kaunti o walang sakit ay kadalasang pasta lang. Mas malamang na kailangan ng root canal kung may matindi o matagal na ngilo sa mainit o malamig, kumikirot na sakit ng ngipin (lalo na sa gabi), masakit kapag kumakagat, may pamamaga o parang tagihawat sa gilagid malapit sa ngipin, o umitim ang ngipin. Kapag naagapan ang butas, madalas naiiwasan ang root canal."},
    {"key": "crown_vs_bridge", "service": "restorative-dentistry",
     "kw": ["difference between a crown", "difference between crown", "vs bridge", "vs. bridge", "versus bridge", "pinagkaiba ng crown"],
     "en": "A crown is a cap that covers and protects one damaged tooth, for example after a root canal or a large filling. A bridge replaces a missing tooth: a false tooth held in place by crowns on the teeth on either side of the gap. Both are custom-made in our own lab, in materials such as zirconia or E.max.",
     "tl": "Ang crown ay parang takip na bumabalot at nagpoprotekta sa isang sirang ngipin, halimbawa pagkatapos ng root canal o malaking pasta. Ang bridge naman ay pamalit sa nawalang ngipin: isang pekeng ngipin na nakakabit sa mga crown ng ngipin sa magkabilang gilid ng puwang. Parehong ginagawa sa sarili naming lab, sa materyales gaya ng zirconia o E.max."},
    {"key": "whitening_types", "service": "cosmetic-dentistry",
     "kw": ["in-office", "in office whitening", "in-clinic whitening", "at-home", "at home whitening", "home whitening", "take-home whitening", "take home whitening", "take-home kit", "laser whitening", "whitening kit", "whitening kits", "chairside"],
     "en": "In-clinic (chairside) whitening is done by your dentist in one visit, in 30-minute cycles (up to 3), and usually brightens teeth about 1 to 2 shades per session. Take-home whitening uses custom-made trays and a professional gel that you wear at home for a set time each day, usually over one to two weeks, for more gradual results. Some patients combine both. Your dentist checks your teeth and gums first.",
     "tl": "Ang in-clinic (chairside) whitening ay ginagawa ng dentista sa isang balik, tig-30 minutong cycle (hanggang 3), at kadalasang pumuputi ang ngipin nang mga 1 hanggang 2 shade bawat session. Ang take-home whitening ay gumagamit ng pasadyang tray at professional na gel na isinusuot sa bahay nang takdang oras araw-araw, kadalasan sa loob ng isa hanggang dalawang linggo, para sa mas unti-unting resulta. May pasyenteng pinagsasama ang dalawa. Titingnan muna ng dentista ang inyong ngipin at gilagid."},
    {"key": "whitening_shades", "service": "cosmetic-dentistry",
     "kw": ["shades lighter", "how many shades", "ilang shade", "how white", "gaano kaputi", "how much whiter"],
     "en": "Results vary from person to person. In-clinic whitening usually brightens teeth about 1 to 2 shades per session, and more with extra sessions or take-home trays. Yellowish stains usually whiten best; grey or very dark stains respond less, and crowns, veneers and fillings don't change color. Your dentist records your starting shade with a shade guide so you can see the difference.",
     "tl": "Iba-iba po ang resulta sa bawat tao. Ang in-clinic whitening ay kadalasang nagpapaputi ng ngipin nang mga 1 hanggang 2 shade bawat session, at mas marami pa sa dagdag na session o take-home tray. Ang madilaw na mantsa ang kadalasang pinakamabilis pumuti; mas mahirap ang kulay-abo o sobrang itim, at hindi nagbabago ang kulay ng crown, veneers at pasta. Itatala ng dentista ang simulang shade gamit ang shade guide para makita ninyo ang pagbabago."},
    {"key": "whitening_sensitivity", "service": "cosmetic-dentistry",
     "kw": ["whitening cause", "whitening sensitivity", "sensitivity after whitening", "whitening sensitive", "whitening hurt", "ngilo sa whitening", "nangingilo pagkatapos ng whitening"],
     "en": "Some people feel temporary sensitivity during or after whitening, usually for a day or two; a desensitizing gel and a toothpaste for sensitive teeth help. Results often last several months to a couple of years, depending on your habits (coffee, tea, soft drinks, smoking), and touch-ups keep them bright.",
     "tl": "May ilang nakakaramdam ng pansamantalang ngilo habang o pagkatapos ng whitening, kadalasan isa o dalawang araw lang; nakakatulong ang desensitizing gel at toothpaste para sa sensitive na ngipin. Ang resulta ay madalas tumatagal nang ilang buwan hanggang dalawang taon, depende sa gawi (kape, tsaa, softdrinks, paninigarilyo), at napapanatili ito ng touch-up."},
    {"key": "veneer_candidate", "service": "cosmetic-dentistry",
     "kw": ["candidate for veneers", "good candidate for veneers", "ruin natural teeth", "ruin my teeth", "ruin my natural", "veneers ruin", "veneers damage", "damage my teeth", "shave my teeth", "filed down", "file my teeth", "sisirain ba ng veneers", "babawasan ba ang ngipin"],
     "en": "You're usually a good candidate if your teeth and gums are healthy and you want to change the color, shape, small gaps or chips of your front teeth. Veneers don't ruin healthy teeth, but porcelain veneers need a thin layer of enamel removed, which can't be undone; E.max needs only a conservative preparation, and composite veneers need little or none. Active decay or gum disease is treated first, and if you grind your teeth your dentist may add a night guard. Your dentist checks your teeth and bite at a consultation.",
     "tl": "Kadalasan po ay bagay kayo sa veneers kung malusog ang ngipin at gilagid at gusto ninyong baguhin ang kulay, hugis, maliit na siwang o tapyas ng ngipin sa harap. Hindi sinisira ng veneers ang malusog na ngipin, pero ang porcelain veneers ay nangangailangan ng manipis na bawas sa enamel na hindi na maibabalik; kaunti lang ang kailangan sa E.max, at kaunti o wala sa composite veneers. Inaayos muna ang butas o sakit sa gilagid, at kung naggigiling kayo ng ngipin, puwedeng magdagdag ng night guard ang dentista. Titingnan ng dentista ang inyong ngipin at kagat sa konsulta."},
    {"key": "smile_preview", "service": "cosmetic-dentistry",
     "kw": ["digital smile design", "dsd", "smile preview", "preview my smile", "preview before", "previews before", "mock-up", "mockup", "see my new smile", "see the result before"],
     "en": "Cosmetic work is planned digitally: your dentist takes photos and intraoral scans, and the design is made with our exocad software and our in-house lab. Your dentist can show you the planned result before any permanent work starts. Ask whether a trial mock-up is possible for your case.",
     "tl": "Digital po ang pagpaplano ng cosmetic na trabaho: kukuha ang dentista ng litrato at intraoral scan, at ididisenyo ito gamit ang aming exocad software at sariling lab. Maipapakita ng dentista ang planong resulta bago simulan ang anumang permanenteng trabaho. Itanong po kung puwede ang trial mock-up para sa inyong kaso."},
    {"key": "aligner_candidate", "service": "orthodontics",
     "kw": ["candidate for clear aligners", "candidate for aligners", "aligners instead", "instead of traditional braces", "instead of braces", "pwede ba ako sa aligners", "bagay ba sa akin ang aligners"],
     "en": "Clear aligners work well for many cases of crowding, spacing and mild to moderate bite problems, for teens and adults who will wear them 20 to 22 hours a day. More complex bite problems or tooth movements are often done better with braces. Your dentist checks with a scan and X-rays and tells you which suits you.",
     "tl": "Maganda ang clear aligners sa maraming kaso ng sungki, siwang at katamtamang problema sa kagat, para sa teens at adults na makakapagsuot nito nang 20 hanggang 22 oras araw-araw. Ang mas komplikadong problema sa kagat ay kadalasang mas maayos gawin sa braces. Titingnan ng dentista gamit ang scan at X-ray at sasabihin kung alin ang bagay sa inyo."},
    {"key": "multi_extraction", "service": "oral-surgery",
     "kw": ["multiple teeth extracted", "extract multiple", "several teeth extracted", "multiple extractions", "more than one extraction", "in one go", "all at once", "sabay-sabay na bunot", "sabay sabay na bunot", "bunutin nang sabay"],
     "en": "Often yes. Several teeth can usually be removed in one visit, depending on your health, which teeth they are and how complex each one is. Your dentist checks with X-rays first and may suggest spreading them over more than one visit for your comfort and healing.",
     "tl": "Kadalasan po, oo. Puwedeng bunutin ang ilang ngipin sa isang balik, depende sa inyong kalusugan, kung aling ngipin, at gaano kahirap ang bawat isa. Titingnan muna ng dentista sa X-ray at puwede niyang imungkahing hatiin ito sa higit sa isang balik para sa inyong ginhawa at paggaling."},
    {"key": "implant_candidate", "service": "oral-surgery",
     "kw": ["candidate for dental implants", "candidate for implants", "candidate for an implant", "missing a tooth for years", "missing for years", "missing for a long time", "matagal nang wala", "matagal nang bungi"],
     "en": "Often yes. When a tooth has been missing for a long time, the jawbone in that spot can shrink, so your dentist checks the bone with a 3D CBCT scan. If there isn't enough bone, bone grafting can often rebuild it before or during implant placement. Healthy gums, good general health and not smoking help implants succeed.",
     "tl": "Kadalasan po, oo. Kapag matagal nang wala ang ngipin, puwedeng lumiit ang buto sa puwestong iyon, kaya titingnan ng dentista ang buto gamit ang 3D CBCT scan. Kung kulang ang buto, madalas itong naaayos sa bone grafting bago o habang inilalagay ang implant. Nakakatulong sa tagumpay ng implant ang malusog na gilagid, maayos na kalusugan at hindi paninigarilyo."},
    {"key": "implant_steps", "service": "oral-surgery",
     "kw": ["step-by-step", "step by step", "process of getting", "entire implant process", "osseointegration", "implant steps", "steps of implant", "proseso ng implant", "paano ang implant"],
     "en": "Getting an implant usually goes like this: 1) consultation and a 3D CBCT scan to plan it; 2) placing the implant in the jawbone, with local anesthesia; 3) healing for about 3 to 6 months while the implant bonds with the bone (osseointegration); 4) attaching the abutment (connector), about 1 to 2 weeks; 5) fitting the final crown made in our lab, about 1 to 2 weeks later. If bone grafting is needed, it adds healing time. Your dentist gives you a timeline for your case.",
     "tl": "Ganito kadalasan ang proseso ng implant: 1) konsulta at 3D CBCT scan para planuhin ito; 2) paglalagay ng implant sa buto, may local anesthesia; 3) paghilom nang mga 3 hanggang 6 na buwan habang kumakapit ang implant sa buto (osseointegration); 4) pagkakabit ng abutment (connector), mga 1 hanggang 2 linggo; 5) pagkakabit ng final crown na gawa sa aming lab, mga 1 hanggang 2 linggo pagkatapos. Kung kailangan ng bone grafting, madadagdagan ang panahon ng paghilom. Bibigyan kayo ng dentista ng timeline para sa inyong kaso."},
    {"key": "ortho_wire", "service": "orthodontics",
     "kw": ["wire is poking", "wire poking", "poking wire", "poking my cheek", "poking my gum", "braces wire", "wire of my braces", "loose bracket", "bracket fell", "bracket came off", "natanggal ang bracket", "tumutusok", "sumusundot"],
     "en": "That's common and usually quick to fix. Cover the end of the wire with orthodontic wax (or a small piece of sugar-free gum), rinse with warm salt water, and call your branch so we can trim or adjust it soon. Don't cut the wire yourself. If a bracket comes loose, keep it and bring it with you.",
     "tl": "Karaniwan po ito at madaling ayusin. Takpan ang dulo ng wire ng orthodontic wax (o maliit na piraso ng sugar-free gum), magmumog ng maligamgam na tubig na may asin, at tumawag sa branch para ma-trim o ma-adjust ito agad. Huwag pong gupitin nang mag-isa ang wire. Kung may natanggal na bracket, itabi ito at dalhin."},
    {"key": "gag", "service": "",
     "kw": ["gag", "gagging", "gag reflex", "naduduwal", "nasusuka", "masusuka", "sensitive gag"],
     "en": "Yes. Tell your dentist before you start. We can take breaks, have you sit more upright, use a numbing spray and work in short steps. For crowns, aligners and many appliances, our intraoral scanners take a digital impression, so you usually don't need a mouthful of impression material.",
     "tl": "Opo. Sabihin po sa dentista bago magsimula. Puwede kaming magpahinga sandali, paupuin kayo nang mas tuwid, gumamit ng pampamanhid na spray, at gawin ito nang paunti-unti. Para sa crown, aligners at maraming appliance, digital impression ang kinukuha ng aming intraoral scanner, kaya kadalasan hindi na kailangan ang maraming impression material sa bibig."},
    {"key": "sterilization", "service": "",
     "kw": ["sterilization", "sterilize", "sterilized", "sterile", "autoclave", "autoclaved", "single-use", "single use", "disposable", "infection control", "safety measures", "safety protocols", "malinis ba", "sanitized", "disinfect"],
     "en": "Your safety comes first. Instruments are cleaned and sterilized in an autoclave between patients, and single-use items such as needles, gloves, masks, bibs and suction tips are used once and thrown away. The dental chair and surfaces are disinfected after every patient.",
     "tl": "Una po ang inyong kaligtasan. Nililinis at ini-sterilize sa autoclave ang mga instrumento bago ang bawat pasyente, at ang mga single-use gaya ng karayom, gloves, mask, bib at suction tip ay isang beses lang ginagamit at itinatapon. Dini-disinfect ang dental chair at mga surface pagkatapos ng bawat pasyente."},
    {"key": "medical_conditions", "service": "",
     "kw": ["heart condition", "heart problem", "high blood pressure", "hypertension", "diabetes", "diabetic", "blood thinner", "blood thinners", "warfarin", "clopidogrel", "medical clearance", "clearance", "altapresyon", "high blood", "sakit sa puso", "may diabetes", "maintenance medicine"],
     "en": "Please tell us about any medical conditions and bring a list of your medicines. For check-ups and cleanings, a clearance usually isn't needed. For extractions, surgery or implants, your dentist may ask for a medical clearance from your doctor, especially with a heart condition, uncontrolled blood pressure or blood sugar, or if you take blood thinners. Don't stop any medicine on your own: your doctor and dentist will decide together.",
     "tl": "Pakisabi po ang inyong mga karamdaman at dalhin ang listahan ng inyong gamot. Sa check-up at cleaning, kadalasan hindi kailangan ng clearance. Sa bunot, surgery o implant, puwedeng humingi ang dentista ng medical clearance mula sa inyong doktor, lalo na kung may sakit sa puso, hindi kontroladong altapresyon o blood sugar, o umiinom ng pampalabnaw ng dugo. Huwag pong ihinto ang anumang gamot nang mag-isa: ang doktor at dentista ang magpapasya nang magkasama."},
    {"key": "post_op", "service": "",
     "kw": ["still hurts", "still bleeding", "still painful", "done yesterday", "procedure yesterday", "is this normal", "should i be worried", "normal ba", "masakit pa rin", "dumudugo pa rin"],
     "en": "Some tenderness for a few days, and light oozing on the first day after an extraction, are normal. Call your branch if the pain is getting worse instead of better after 2 to 3 days, if bleeding doesn't stop after 30 minutes of biting firmly on gauze, if you have a fever or a bad taste, or if something feels loose. For severe swelling, trouble breathing or swallowing, or bleeding that won't stop, go to the nearest hospital emergency room.",
     "tl": "Normal po ang kaunting pananakit nang ilang araw, at bahagyang pagdurugo sa unang araw pagkatapos ng bunot. Tumawag po sa branch kung lumalala ang sakit sa halip na gumagaan pagkatapos ng 2 hanggang 3 araw, kung hindi tumitigil ang dugo pagkatapos kagatin nang mariin ang gauze nang 30 minuto, kung may lagnat o hindi magandang lasa, o kung may parang maluwag. Kung matindi ang pamamaga, hirap huminga o lumunok, o hindi tumitigil ang pagdurugo, pumunta agad sa pinakamalapit na emergency room."},
    {"key": "eat_brush_after", "service": "",
     "kw": ["eat or brush", "brush normally", "eat normally", "when can i eat", "when can i brush", "kailan pwede kumain", "kailan puwede kumain", "kailan pwede magsipilyo", "kailan puwede magsipilyo"],
     "en": "It depends on the treatment. After anything with anesthesia, wait until the numbness wears off before eating so you don't bite your cheek or tongue. After an extraction, eat soft, cool food for the first day or two, and brush gently from the next day, avoiding the area. After whitening, avoid staining food and drinks for 48 hours. After fluoride varnish, don't eat or brush for 4 to 6 hours. Your dentist will give you instructions for your treatment.",
     "tl": "Depende po sa treatment. Kung may anesthesia, hintayin munang mawala ang pamamanhid bago kumain para hindi makagat ang pisngi o dila. Pagkatapos ng bunot, malambot at malamig na pagkain muna sa unang isa o dalawang araw, at dahan-dahang magsipilyo mula kinabukasan, iwasan ang lugar na binunutan. Pagkatapos ng whitening, iwasan ang nakakamantsang pagkain at inumin nang 48 oras. Pagkatapos ng fluoride varnish, huwag kumain o magsipilyo nang 4 hanggang 6 na oras. Bibigyan kayo ng dentista ng tagubilin para sa inyong treatment."},
    {"key": "med_cert", "service": "",
     "kw": ["medical certificate", "med cert", "medcert", "dental certificate", "certificate", "excuse letter", "excuse slip", "sick leave"],
     "en": "Yes. Your dentist can give you a dental certificate for your visit or treatment, for work or school. Just ask at the front desk or tell your dentist during your appointment.",
     "tl": "Opo. Puwede kayong bigyan ng dentista ng dental certificate para sa inyong visit o treatment, para sa trabaho o eskuwela. Sabihin lang po sa front desk o sa dentista habang nasa appointment."},
    {"key": "sedation_options", "service": "pediatric-dentistry",
     "kw": ["laughing gas", "nitrous", "nitrous oxide", "iv sedation", "oral sedative", "oral sedatives", "oral sedation", "sedatives"],
     "en": "We offer conscious sedation when it's appropriate, most often for very anxious children and patients with special needs: you stay awake but relaxed, and you're monitored throughout. For other options such as laughing gas or IV sedation, please ask your branch. If you're very nervous, tell us: we go slowly, explain every step, and you can ask to stop anytime.",
     "tl": "May conscious sedation po kami kapag angkop, kadalasan para sa sobrang kinakabahang bata at pasyenteng may special needs: gising kayo pero relaxed, at binabantayan sa buong treatment. Para sa ibang opsyon gaya ng laughing gas o IV sedation, pakitanong po sa branch. Kung sobra kayong kinakabahan, sabihin lang: dahan-dahan kami, ipinapaliwanag ang bawat hakbang, at puwede kayong humingi ng hinto anumang oras."},
]
