"""Dental Haven fee schedule (billing price list), from the clinic's SERVICES.xlsx (Oct 1, 2026).

Names are kept exactly as in MyMedsPH so old bills match. Internal use (billing, progress notes) — the public website
price list is separate (prices_content.py). (name, unit, price in centavos, category)."""

CATEGORIES = [
    'Consultation & Check-up',
    'X-ray, Scans, Impressions & Records',
    'Cleaning & Prevention',
    'Fillings & Restorations',
    'Root Canal (Endodontics)',
    'Extraction & Oral Surgery',
    'Crowns, Bridges & Veneers',
    'Inlays, Onlays & Overlays',
    'Dentures',
    'Implants & Bone Graft',
    'Braces, Aligners & Orthodontics',
    'Retainers & Ortho Appliances',
    'TMJ, Splints & Guards',
    'Whitening & Cosmetic',
    'Pediatric (Kids)',
    'Fees & Charges',
]

FEES = [
    ('CONSULTATION FEE PEDIATRIC', '', 65000, 'Consultation & Check-up'),
    ('PEDIATRIC EXTRACTION', 'Per tooth', 98000, 'Pediatric (Kids)'),
    ('PULPO-SSC', '', 500000, 'Pediatric (Kids)'),
    ('DISKING', '', 60000, 'Pediatric (Kids)'),
    ('PULPO + SOC', '', 450000, 'Pediatric (Kids)'),
    ('ORAL PROPHYLAXIS (MILD)', '', 98000, 'Cleaning & Prevention'),
    ('ORAL PROPHYLAXIS WITH TOPICAL FLUORIDE', '', 280000, 'Cleaning & Prevention'),
    ('BANK PERCENTAGE', 'Debit and Credit Card - 5%', 0, 'Fees & Charges'),
    ('CONSULTATION', '', 65000, 'Consultation & Check-up'),
    ('ORAL PROPHYLAXIS (MODERATE)', '', 170000, 'Cleaning & Prevention'),
    ('ORAL PROPHYLAXIS (SEVERE)', '', 230000, 'Cleaning & Prevention'),
    ('NICOTINE STAIN', '', 50000, 'Cleaning & Prevention'),
    ('GUM CARE (MED)', '', 10000, 'Cleaning & Prevention'),
    ('RESTORATION/PASTA- POSTERIOR/LIKOD', 'Per Surface', 98000, 'Fillings & Restorations'),
    ('RESTORATION/PASTA-ANTERIOR/HARAP', 'Per Surface', 120000, 'Fillings & Restorations'),
    ('RESTORATION/PASTA-CLASS 2/ PAGITAN', 'Per Surface', 250000, 'Fillings & Restorations'),
    ('RESTORATION- DIASTEMA CLOSURE', 'Per tooth', 370000, 'Fillings & Restorations'),
    ('BASE/GI', '', 55000, 'Fillings & Restorations'),
    ('CAVITY LINER/ GAMOT', '', 55000, 'Fillings & Restorations'),
    ('EXTRACTION- ANTERIOR/POSTERIOR', 'Per tooth', 98000, 'Extraction & Oral Surgery'),
    ('EXTRACTION-THIRD MOLAR', 'Per tooth', 350000, 'Extraction & Oral Surgery'),
    ('EXTRACTION- COMPLICATED CASE', 'Per tooth', 400000, 'Extraction & Oral Surgery'),
    ('ADDITIONAL ANESTHESIA (LIDOCAINE)', '', 60000, 'Extraction & Oral Surgery'),
    ('ODONTECTOMY- MINIMUM', 'Per tooth', 1050000, 'Extraction & Oral Surgery'),
    ('ODONTECTOMY- DIFFICULT CASE', 'Per tooth', 2500000, 'Extraction & Oral Surgery'),
    ('GINGIVECTOMY', 'Per arch', 1050000, 'Extraction & Oral Surgery'),
    ('APICOECTOMY', '', 1000000, 'Root Canal (Endodontics)'),
    ('RCT-CANAL TREATMENT W/ LESION', '', 1250000, 'Root Canal (Endodontics)'),
    ('RCT- INTERNAL BLEACHING', '', 1000000, 'Whitening & Cosmetic'),
    ('POST AND CORE - PORCELAIN', '', 1050000, 'Root Canal (Endodontics)'),
    ('POST AND CORE - FIBER POST', '', 650000, 'Root Canal (Endodontics)'),
    ('RUBBERIZED MOUTHGUARD', '', 850000, 'TMJ, Splints & Guards'),
    ('NIGHT GUARD', 'Per arch', 850000, 'TMJ, Splints & Guards'),
    ('BLEACHING TRAY', '', 600000, 'Whitening & Cosmetic'),
    ('INTRAORAL PHOTO', '', 100000, 'X-ray, Scans, Impressions & Records'),
    ('ASEPSIS FEE', 'FOR ORTHO CASE', 30000, 'Braces, Aligners & Orthodontics'),
    ('WHITENING/CHAIRSIDE BLEACHING', 'Per cycle', 1000000, 'Whitening & Cosmetic'),
    ('TOOTH BUILD UP', 'Per tooth', 450000, 'Fillings & Restorations'),
    ('ONLAY- RESIN', 'Per unit', 600000, 'Inlays, Onlays & Overlays'),
    ('ONLAY- 3D PRINTED PMMA', 'Per unit / Per tooth', 850000, 'Inlays, Onlays & Overlays'),
    ('ONLAY- PORCELAIN', 'Per unit', 1550000, 'Inlays, Onlays & Overlays'),
    ('INLAY- RESIN', 'Per unit / Per tooth', 600000, 'Inlays, Onlays & Overlays'),
    ('INLAY- 3D PRINTED PMMA', 'Per unit / Per tooth', 850000, 'Inlays, Onlays & Overlays'),
    ('INLAY- PORCELAIN', 'Per unit / Per tooth', 1550000, 'Inlays, Onlays & Overlays'),
    ('VENEERS - PORCELAIN EMAX (BRANDED)', 'Per unit / Per tooth', 3500000, 'Crowns, Bridges & Veneers'),
    ('VENEERS- CERAMIC', 'Per unit / Per tooth', 2500000, 'Crowns, Bridges & Veneers'),
    ('VENEERS- CERAMAGE / 3D PRINTED', 'Per unit / Per tooth', 1500000, 'Crowns, Bridges & Veneers'),
    ('VENEERS- INDIRECT COMPOSITE', 'Per unit / Per tooth', 1050000, 'Crowns, Bridges & Veneers'),
    ('VENEERS- DIRECT COMPOSITE', 'Per unit / Per tooth', 1000000, 'Crowns, Bridges & Veneers'),
    ('BRACES INSTALL', '', 0, 'Braces, Aligners & Orthodontics'),
    ('BRACES REMOVAL UPPER AND LOWER', 'Free Mild OP only', 450000, 'Braces, Aligners & Orthodontics'),
    ("BITE PLANE (CATLAN'S APPLIANCE)", 'Per arch', 1000000, 'Retainers & Ortho Appliances'),
    ('EXPANDER', 'Per Arch', 1000000, 'Retainers & Ortho Appliances'),
    ('OCCLUSAL SPLINT (TMJ TREATMENT)', '', 5500000, 'TMJ, Splints & Guards'),
    ('ORTHO SPLINT', 'Per arch', 850000, 'Retainers & Ortho Appliances'),
    ('ALL METAL RETAINER', 'Per arch', 1200000, 'Retainers & Ortho Appliances'),
    ('INVISIBLE RETAINER', 'Per arch', 1000000, 'Retainers & Ortho Appliances'),
    ('HAWLEY RETAINER', 'Per arch', 800000, 'Retainers & Ortho Appliances'),
    ('LINGUAL RETAINER', 'Per arch', 1000000, 'Retainers & Ortho Appliances'),
    ('FIXED BRIDGE - PORCELAIN EMAX', 'Per unit / Per tooth', 3500000, 'Crowns, Bridges & Veneers'),
    ('FIXED BRIDGE- ZIRCONIA', 'Per unit / Per tooth', 2500000, 'Crowns, Bridges & Veneers'),
    ('FIXED BRIDGE- CERAMIC', 'Per unit / Per tooth', 2000000, 'Crowns, Bridges & Veneers'),
    ('FIXED BRIDGE- CERAMAGE / 3D PRINTED', 'Per unit / Per tooth', 1500000, 'Crowns, Bridges & Veneers'),
    ('JACKET CROWN - MILLED PMMA', 'Per unit / Per tooth', 1800000, 'Crowns, Bridges & Veneers'),
    ('JACKET CROWN- FIBER REINFORCED', 'Per unit / Per tooth', 1050000, 'Crowns, Bridges & Veneers'),
    ('JACKET CROWN- TEMPORARY', 'Per unit / Per tooth', 150000, 'Crowns, Bridges & Veneers'),
    ('PEDIATRIC- SEALANT', '', 100000, 'Pediatric (Kids)'),
    ('PEDIATRIC- STAINLESS STEEL CROWN', '', 450000, 'Pediatric (Kids)'),
    ('PEDIATRIC- STRIP OFF CROWN', 'Per Crown', 300000, 'Pediatric (Kids)'),
    ('PEDIATRIC- SPACE MAINTANER', '', 870000, 'Pediatric (Kids)'),
    ('PEDIATRIC- EXPANDER', 'Per arch', 1000000, 'Pediatric (Kids)'),
    ('PEDIATRIC- PULPECTOMY', 'Per Canal', 900000, 'Pediatric (Kids)'),
    ('REBRACKET - ORDINARY', 'Per bracket', 20000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (METAL BRACES-CLASS 1) (45K-60K)', '', 4500000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (METAL BRACES-CLASS 2) (50K - 70K)', '', 6000000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (METAL BRACES -CLASS 3) (55K - 80K)', '', 5500000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (CERAMIC BRACES-CLASS 1)', '', 6000000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (CERAMIC BRACES-CLASS 2)', '', 7000000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (CERAMIC BRACES-CLASS 3)', '', 8000000, 'Braces, Aligners & Orthodontics'),
    ('XRAY - PERIAPICAL', '', 60000, 'X-ray, Scans, Impressions & Records'),
    ('ORTHODONTIC TREATMENT (SAPPHIRE BRACES-CLASS 1)', '', 7000000, 'Braces, Aligners & Orthodontics'),
    ('FIXED BRIDGE - INSTALL', '', 0, 'Crowns, Bridges & Veneers'),
    ('ONLAY - INSTALL', '', 0, 'Inlays, Onlays & Overlays'),
    ('INLAY - INSTALL', '', 0, 'Inlays, Onlays & Overlays'),
    ('ORTHODONTIC TREATMENT (SAPPHIRE BRACES-CLASS 2)', '', 8000000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (SAPPHIRE BRACES-CLASS 3)', '', 9000000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (SELF LIGATING BRACES-CLASS 1)', '', 8000000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (SELF LIGATING BRACES-CLASS2)', '', 9000000, 'Braces, Aligners & Orthodontics'),
    ('ORTHODONTIC TREATMENT (SELF LIGATING BRACES-CLASS 3)', '', 10000000, 'Braces, Aligners & Orthodontics'),
    ('BRACES ADJUSTMENT', '', 0, 'Braces, Aligners & Orthodontics'),
    ('DENTURE ADJUSTMENT', '', 0, 'Dentures'),
    ('INSTALL DENTURE', '', 0, 'Dentures'),
    ('FOLLOW UP CHECK UP', '', 0, 'Consultation & Check-up'),
    ('RCT - 2 CANALS', '', 1700000, 'Root Canal (Endodontics)'),
    ('RCT- 3 CANALS', '', 2550000, 'Root Canal (Endodontics)'),
    ('DENTURE TRIAL', '', 0, 'Dentures'),
    ('DENTURE IMPRESSION', '', 0, 'X-ray, Scans, Impressions & Records'),
    ('CHECK UP', '', 0, 'Consultation & Check-up'),
    ('SUTURE REMOVAL', '', 0, 'Extraction & Oral Surgery'),
    ('INSTALL - RETAINER', '', 0, 'Retainers & Ortho Appliances'),
    ('PULPOTOMY', '', 600000, 'Root Canal (Endodontics)'),
    ('ADULT FLUORIDE', 'WALANG OP', 185000, 'Cleaning & Prevention'),
    ('ELASTICS', '', 10000, 'Braces, Aligners & Orthodontics'),
    ('FRENECTOMY', '', 1000000, 'Extraction & Oral Surgery'),
    ('REPLACEMENT OF BRACKET - ORDINARY', 'Ordinary', 30000, 'Braces, Aligners & Orthodontics'),
    ('INSTALL LOWER BRACES', '', 0, 'Braces, Aligners & Orthodontics'),
    ('BRACES REMOVAL UPPER BRACES OR LOWER BRACES ONLY', 'Free Mild Cleaning ang Polishing', 300000, 'Braces, Aligners & Orthodontics'),
    ('REBRACKET - BUCCAL TUBE', 'Per bracket', 30000, 'Braces, Aligners & Orthodontics'),
    ('REPLACEMENT - BUCCAL TUBE', 'Per Buccal Tube', 60000, 'Braces, Aligners & Orthodontics'),
    ('ASEPSIS FEE - COMPLETE', '', 0, 'Braces, Aligners & Orthodontics'),
    ('ASEPSIS FEE - INCOMPLETE', '', 15000, 'Braces, Aligners & Orthodontics'),
    ('PONTIC', 'Per pontic', 60000, 'Crowns, Bridges & Veneers'),
    ('FIXED BRIDGE - IMPRESSION', '', 0, 'X-ray, Scans, Impressions & Records'),
    ('JACKET CROWN - IMPRESSION', '', 0, 'X-ray, Scans, Impressions & Records'),
    ('VENEERS - IMPRESSION', '', 0, 'X-ray, Scans, Impressions & Records'),
    ('REPLACEMENT OF BRACKET FOR CERAMIC BRACES', 'Per bracket', 100000, 'Braces, Aligners & Orthodontics'),
    ('REPLACEMENT OF BRACKET FOR SAPPHIRE BRACES', 'Per bracket', 250000, 'Braces, Aligners & Orthodontics'),
    ('REPLACEMENT OF BRACKET FOR SELF-LIGATING BRACES', 'Per bracket', 250000, 'Braces, Aligners & Orthodontics'),
    ('JACKET CROWN - INSTALL', '', 0, 'Crowns, Bridges & Veneers'),
    ('VENEERS - INSTALL', '', 0, 'Crowns, Bridges & Veneers'),
    ('PANORAMIC XRAY', '', 100000, 'X-ray, Scans, Impressions & Records'),
    ('CEPHALOMETRIC XRAY - LATERAL VIEW', '', 100000, 'X-ray, Scans, Impressions & Records'),
    ('CEPHALOMETRIC XRAY - PA VIEW', '', 100000, 'X-ray, Scans, Impressions & Records'),
    ('TMJ XRAY - REST AND CLOSE VIEW', '', 100000, 'X-ray, Scans, Impressions & Records'),
    ('TMJ XRAY- OPEN AND CLOSE VIEW', '', 100000, 'X-ray, Scans, Impressions & Records'),
    ('DEMOGRAPHER', 'TMJ', 500000, 'TMJ, Splints & Guards'),
    ('UPPER IMPRESSION', '', 0, 'X-ray, Scans, Impressions & Records'),
    ('LOWER IMPRESSION', '', 0, 'X-ray, Scans, Impressions & Records'),
    ('FIXED BRIDGE / CROWN REMOVAL', 'Per unit / Per tooth', 100000, 'Crowns, Bridges & Veneers'),
    ('PEDIATRIC-PULPOTOMY', 'Per canal without Lesion', 950000, 'Pediatric (Kids)'),
    ('UPPER AND LOWER IMPRESSION', '', 0, 'X-ray, Scans, Impressions & Records'),
    ('ROOT CANAL TREATMENT', 'Per Canal with Lesion', 1250000, 'Root Canal (Endodontics)'),
    ('RCT - RETREATMENT', 'Per Canal', 1500000, 'Root Canal (Endodontics)'),
    ('MOCK UP', '', 500000, 'X-ray, Scans, Impressions & Records'),
    ('BITE ANALYSIS AND DEPROGRAMMER', '', 600000, 'TMJ, Splints & Guards'),
    ('BITE (REGISTRATION)', '', 0, 'X-ray, Scans, Impressions & Records'),
    ('BRACES REMOVAL UPPER AND LOWER (UNFINISH CONTRACT)', 'with free polishing', 450000, 'Braces, Aligners & Orthodontics'),
    ('CARPAL RADIOGRAPH', '', 100000, 'X-ray, Scans, Impressions & Records'),
    ('DENTURE RELINING', 'Per arch', 300000, 'Dentures'),
    ('INSTALL - SPLINT', '', 0, 'TMJ, Splints & Guards'),
    ('REBRACKET - SELF LIGATING', 'Normal bracket', 55000, 'Braces, Aligners & Orthodontics'),
    ('REBRACKET - CERAMIC BRACES', 'Normal bracket', 55000, 'Braces, Aligners & Orthodontics'),
    ('REBRACKET - SAPPHIRE BRACES', 'Normal bracket', 55000, 'Braces, Aligners & Orthodontics'),
    ('REPLACEMENT - SEL LIGATING BRACES', 'Normal bracket', 200000, 'Braces, Aligners & Orthodontics'),
    ('REPLACEMENT - CERAMIC BRACES', 'Normal bracket', 100000, 'Braces, Aligners & Orthodontics'),
    ('REPLACEMENT - SAPPHIRE BRACES', 'Normal bracket', 200000, 'Braces, Aligners & Orthodontics'),
    ('REPLACEMENT - SEL LIGATING BRACES', 'Buccal Tube', 250000, 'Braces, Aligners & Orthodontics'),
    ('REPLACEMENT - CERAMIC BRACES', 'Buccal Tube', 150000, 'Braces, Aligners & Orthodontics'),
    ('REPLACEMENT - SAPPHIRE BRACES', 'Buccal Tube', 200000, 'Braces, Aligners & Orthodontics'),
    ('INSTALL - EXPANDER', 'Upper and Lower', 0, 'Retainers & Ortho Appliances'),
    ('INSTALL EXPANDER', 'Upper only', 0, 'Retainers & Ortho Appliances'),
    ('INSTALL EXPANDER', 'Lower only', 0, 'Retainers & Ortho Appliances'),
    ('OBTURATION', '', 0, 'Root Canal (Endodontics)'),
    ('FIXED BRIDGE - TEMPORARY', 'Per unit / Per tooth', 150000, 'Crowns, Bridges & Veneers'),
    ('ROOT CANAL - RE TREATMENT', 'Per CANAL', 1550000, 'Root Canal (Endodontics)'),
    ('ODONTECTOMY - SPECIAL CASE', 'Per tooth', 3500000, 'Extraction & Oral Surgery'),
    ('PANORAMIC XRAY', 'No bite', 100000, 'X-ray, Scans, Impressions & Records'),
    ('DIGITAL IMPRESSION', '', 100000, 'X-ray, Scans, Impressions & Records'),
    ('LIGUAL BUTTON', 'Rebracket', 20000, 'Braces, Aligners & Orthodontics'),
    ('LINGUAL- BUTTON', 'Replacement', 30000, 'Braces, Aligners & Orthodontics'),
    ('LINGUAL BUTTON -REB', 'Rebracket', 20000, 'Braces, Aligners & Orthodontics'),
    ('IMPLANT', 'Per Unit', 0, 'Implants & Bone Graft'),
    ('IMPLANT.', 'Per Unit', 10000000, 'Implants & Bone Graft'),
    ('TADS', 'PER TADS', 700000, 'Braces, Aligners & Orthodontics'),
    ('ADDITIONAL ANESTHESIA (ARTICAINE)', '', 60000, 'Extraction & Oral Surgery'),
    ('ADDITIONAL ANESTHESIA (MEPIVACAINE)', '', 60000, 'Extraction & Oral Surgery'),
    ('CBCT SCAN', 'FULL', 850000, 'X-ray, Scans, Impressions & Records'),
    ('CBCT SCAN - 6×8', '6×8', 550000, 'X-ray, Scans, Impressions & Records'),
    ('CBCT SCAN - 12×9', '12×9', 750000, 'X-ray, Scans, Impressions & Records'),
    ('CBCT SCAN -3×3', '3×3', 350000, 'X-ray, Scans, Impressions & Records'),
    ('HMO- ASEPSIS FEE', '', 55000, 'Fees & Charges'),
    ('DEEP SCALLING', '', 250000, 'Cleaning & Prevention'),
    ('SILVER DIAMINE', 'Per Quadrant', 120000, 'Cleaning & Prevention'),
    ('RESIN INFILTRATION ICON', 'Per tooth', 250000, 'Fillings & Restorations'),
    ('RESTORATION/ PASTA -CLASS 5', 'Per Surface', 120000, 'Fillings & Restorations'),
    ('SUTURE', 'Per suture', 60000, 'Extraction & Oral Surgery'),
    ('SEDATION', '', 3500000, 'Extraction & Oral Surgery'),
    ('JACKET CROWN - CERAMIC', 'Per unit / Per tooth', 2000000, 'Crowns, Bridges & Veneers'),
    ('JACKET CROWN - ZIRCONIA', 'Per unit / Per tooth', 2500000, 'Crowns, Bridges & Veneers'),
    ('JACKET CROWN - EMAX', 'Per unit / Per tooth', 3000000, 'Crowns, Bridges & Veneers'),
    ('TAKE HOME BLEACHING', '', 1500000, 'Whitening & Cosmetic'),
    ('CROWN LENGTHENING', 'Per Crown / Per tooth', 850000, 'Extraction & Oral Surgery'),
    ('INLAY - MILLED PMMA', 'Per unit / Per tooth', 1050000, 'Inlays, Onlays & Overlays'),
    ('ONLAY - MILLED PMMA', 'Per unit / Per tooth', 1050000, 'Inlays, Onlays & Overlays'),
    ('OVERLAY -PORCELAIN', 'Per unit / Per tooth', 1550000, 'Inlays, Onlays & Overlays'),
    ('OVERLAY - MILLED PMMA', '', 1050000, 'Inlays, Onlays & Overlays'),
    ('OVERLAY - 3D PRINTED PMMA', 'Per unit / Per tooth', 850000, 'Inlays, Onlays & Overlays'),
    ('OVERLAY - INSTALL', '', 0, 'Inlays, Onlays & Overlays'),
    ('JACKET CROWN - PORCELAIN EMAX', 'Per unit / Per tooth', 3500000, 'Crowns, Bridges & Veneers'),
    ('JACKET CROWN - 3D PRINTED', 'Per unit / Per tooth', 1500000, 'Crowns, Bridges & Veneers'),
    ('FIXED BRIDGE - MILLED PMMA', 'Per unit / Per tooth', 1800000, 'Crowns, Bridges & Veneers'),
    ('FIXED BRIDGE - EMAX', 'Per unit / Per tooth', 3000000, 'Crowns, Bridges & Veneers'),
    ('VENEERS - ZIRCONIA', 'Per unit / Per tooth', 3000000, 'Crowns, Bridges & Veneers'),
    ('EXTRAORAL PHOTO', '', 100000, 'X-ray, Scans, Impressions & Records'),
    ('CLEAR ALIGNERS', 'Minimum', 16000000, 'Braces, Aligners & Orthodontics'),
    ('WRAP AROUND HAWLEY RETAINER', 'Per arch', 850000, 'Retainers & Ortho Appliances'),
    ('DENTURE - IVOCAP BASE (BRANDED)', '1-6 Missing teeth', 3500000, 'Dentures'),
    ('DENTURE - FLEXIBLE BASE (RUBBER)', '1-6 Missing teeth', 2550000, 'Dentures'),
    ('DENTURE - BASIS HIGH (JAPAN MADE)', '1-6 Missing teeth', 1500000, 'Dentures'),
    ('DENTURE - LUCITONE BASE (GERMANY MADE)', '1-6 Missing teeth', 1350000, 'Dentures'),
    ('DENTURE - ORDINARY BASE', '1-6 Missing teeth', 950000, 'Dentures'),
    ('DENTURE REBASE', 'Per arch', 300000, 'Dentures'),
    ('DENTURE CRACK REPAIR', 'Per arch', 250000, 'Dentures'),
    ('RUSH FEE - DENTURE', '0.2', 0, 'Fees & Charges'),
    ('RUSH FEE - ZIRCONIA EMAX', '0.2', 0, 'Fees & Charges'),
    ('INDIVIDUAL TRAY', 'Per arch', 150000, 'X-ray, Scans, Impressions & Records'),
    ('ORTHO CAST M- 3D PRINTED', 'Per arch', 60000, 'X-ray, Scans, Impressions & Records'),
    ('MODEL CAST', 'Per arch', 50000, 'X-ray, Scans, Impressions & Records'),
    ('ROOT CANAL TRATMENT', 'Per Canal Without Lesion', 950000, 'Root Canal (Endodontics)'),
    ('DENTURE - IVOCAP BASE', '7 - COMPLETE', 3750000, 'Dentures'),
    ('DENTURE - FLEXIBLE BASE - RUBBER', '7 - COMPLETE', 2950000, 'Dentures'),
    ('DENTURE - BASIS HIGH - JAPAN MADE', '7 - COMPLETE', 1850000, 'Dentures'),
    ('DENTURE - LUCITONE BASE - GERMANY MADE', '7 - COMPLETE', 1600000, 'Dentures'),
    ('DENTURE - ORDINARY BASE COMPLETE', '7 - COMPLETE', 1150000, 'Dentures'),
    ('BOME GRAFT', 'Per Unit', 3500000, 'Implants & Bone Graft'),
    ('CLINCHECK FOR ALIGNERS', 'PER CASE', 850000, 'X-ray, Scans, Impressions & Records'),
]
