"""Dental Haven consumables: the clinic's item list (592 items, from the clinic's inventory master list),
sorted into the clinic's categories. Loaded once into Inventory; staff edit items there afterwards."""

INVENTORY_VERSION = 1

# Category groups, in display order.
GROUPS = {
    'General & Preventive Care': ['Routine Disposables', 'Preventive Materials', 'Diagnostic Consumables'],
    'Clinical Specialties & Treatments': ['Restorative & Cosmetic', 'Endodontic (Root Canal)', 'Prosthodontic & Impression', 'Surgical, Periodontal & Implant', 'Orthodontic'],
    'Clinic Infrastructure & Safety': ['Infection Control & PPE', 'Anesthetics & Pharmaceuticals', 'Laboratory Consumables'],
    'Other Supplies': ['Patient Take-home Items', 'Instruments & Small Equipment', 'Office & Admin Supplies', 'Housekeeping'],
}
CATEGORIES = [c for cs in GROUPS.values() for c in cs]
GROUP_OF = {c: g for g, cs in GROUPS.items() for c in cs}

# (name, unit, category)
ITEMS = [
    ('Bib', 'pack', 'Routine Disposables'),
    ('Bib Clip', 'piece', 'Routine Disposables'),
    ("Cotton Ball (300's)", 'pack', 'Routine Disposables'),
    ('Cotton Balls (1600s)', 'pack', 'Routine Disposables'),
    ('Cotton Buds', 'pack', 'Routine Disposables'),
    ('Cotton Gauze', 'pack', 'Routine Disposables'),
    ('Cotton Roll', 'pack', 'Routine Disposables'),
    ('Cotton Swab', 'box', 'Routine Disposables'),
    ('Defog', 'bottle', 'Routine Disposables'),
    ('Dental Applicator Tip', 'pack', 'Routine Disposables'),
    ('Glycerin (Orex)', 'bottle', 'Routine Disposables'),
    ('Micro Applicator Brush', 'pack', 'Routine Disposables'),
    ('Micro Applicator Tip', 'pack', 'Routine Disposables'),
    ('Paper Bag (Small)', 'piece', 'Routine Disposables'),
    ('Petroleum Jelly (25g)', 'bottle', 'Routine Disposables'),
    ('Silicon Dappen Dish', 'piece', 'Routine Disposables'),
    ('Suction Tip', 'pack', 'Routine Disposables'),
    ('Tissue (8pcs)', 'pack', 'Routine Disposables'),
    ('Tissue (BIG)', 'pack', 'Routine Disposables'),
    ('Towel Assorted (12pcs)', 'pack', 'Routine Disposables'),
    ('Towel Plain (12pcs)', 'pack', 'Routine Disposables'),
    ('Dental Floss (Big)', 'piece', 'Preventive Materials'),
    ('Dental Floss Pick', 'pack', 'Preventive Materials'),
    ('Floss Threader', 'set', 'Preventive Materials'),
    ('Fluoride (V-Varnish)', 'piece', 'Preventive Materials'),
    ('Mouthwash (Colgate Plax)', 'liter', 'Preventive Materials'),
    ('Prophy Brush', 'pack', 'Preventive Materials'),
    ('Prophy Cup', 'piece', 'Preventive Materials'),
    ('ProphyTech Paste', 'bottle', 'Preventive Materials'),
    ('Sealant', 'piece', 'Preventive Materials'),
    ('Silver Diamine Fluoride (Topamine)', 'bottle', 'Preventive Materials'),
    ('Tooth Paste (Colgate)', 'tube', 'Preventive Materials'),
    ('Articulating Paper', 'box', 'Diagnostic Consumables'),
    ('Articulating Paper /pad', 'pad', 'Diagnostic Consumables'),
    ('Articulating Paper U-Shaped', 'pad', 'Diagnostic Consumables'),
    ('Reveal Carries Indicator', 'bottle', 'Diagnostic Consumables'),
    ('X-ray Censor Plastic', 'pack', 'Diagnostic Consumables'),
    ('X-ray Positioner', 'set', 'Diagnostic Consumables'),
    ('Astro Brush', 'piece', 'Restorative & Cosmetic'),
    ('Blue Shine', 'bottle', 'Restorative & Cosmetic'),
    ('Bonding Agent (3M)', 'bottle', 'Restorative & Cosmetic'),
    ('Bonding Agent (BC Plus)', 'bottle', 'Restorative & Cosmetic'),
    ('Bonding Agent (TETRIC)', 'bottle', 'Restorative & Cosmetic'),
    ('Burs (Finishing Straight) Yellow', 'set', 'Restorative & Cosmetic'),
    ('Burs (Round) Blue', 'set', 'Restorative & Cosmetic'),
    ('Celluloid Strip', 'box', 'Restorative & Cosmetic'),
    ('Charmcore A2', 'piece', 'Restorative & Cosmetic'),
    ('Charmcore Tip', 'pack', 'Restorative & Cosmetic'),
    ('Composite A1 (3M)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A1 (PALFIQUE)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A1B (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A1D (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A1E (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A2 (3M)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A2 (IVOCLAR)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A2 (PALFIQUE)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A2B (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A2D (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A2E (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A3 (3M)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A3 (PALFIQUE)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A3.5 (3M)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A3B (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A3D (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite A3E (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite I (ESTELITE) Tokuyama', 'tube', 'Restorative & Cosmetic'),
    ('Composite I (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite WB (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite WD (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Composite WE (FORMA)', 'tube', 'Restorative & Cosmetic'),
    ('Coupling Agent (Silane)', 'bottle', 'Restorative & Cosmetic'),
    ('Dental Tape (Teflon)', 'roll', 'Restorative & Cosmetic'),
    ('Dentin Desensitizer', 'bottle', 'Restorative & Cosmetic'),
    ('Etchant (Primo Etch)', 'syringe', 'Restorative & Cosmetic'),
    ('Finishing Polishing Strip (White/Gray)', 'pack', 'Restorative & Cosmetic'),
    ('Flowable A1 (3M)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A1 (B&E)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A1 (Kerr)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A2 (3M)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A2 (B&E)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A2 (Kerr)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A3 (3M)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A3 (B&E)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A3 (Kerr)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A3.5 (3M)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A3.5 (B&E)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable A3.5 (Kerr)', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable Geanial A2', 'syringe', 'Restorative & Cosmetic'),
    ('Flowable Geanial JE', 'syringe', 'Restorative & Cosmetic'),
    ('G.C Modeling Liquid', 'bottle', 'Restorative & Cosmetic'),
    ('G.I Cement', 'set', 'Restorative & Cosmetic'),
    ('G.I Cement (Fuji) Red', 'set', 'Restorative & Cosmetic'),
    ('G.I Cement IX', 'set', 'Restorative & Cosmetic'),
    ('G.I Fusion (Flowable)', 'syringe', 'Restorative & Cosmetic'),
    ('G.I. Mixing Pad', 'pad', 'Restorative & Cosmetic'),
    ('Glycerin Gel', 'bottle', 'Restorative & Cosmetic'),
    ('Gum Barrier', 'piece', 'Restorative & Cosmetic'),
    ('ICON', 'set', 'Restorative & Cosmetic'),
    ('IRM', 'set', 'Restorative & Cosmetic'),
    ('Liner (Cal LC)', 'syringe', 'Restorative & Cosmetic'),
    ('Matrix Band (Big)', 'pack', 'Restorative & Cosmetic'),
    ('Matrix Band (Small)', 'pack', 'Restorative & Cosmetic'),
    ('Matrix Band Pre-form (Blue)', 'piece', 'Restorative & Cosmetic'),
    ('Matrix Band Pre-form (Green)', 'set', 'Restorative & Cosmetic'),
    ('Metal Polishing Strip', 'pack', 'Restorative & Cosmetic'),
    ('Opalescence Boost', 'set', 'Restorative & Cosmetic'),
    ('Optrasculpt (Gray)', 'pack', 'Restorative & Cosmetic'),
    ('Optrasculpt Pad (Gray) /piece', 'piece', 'Restorative & Cosmetic'),
    ('Optrasculpt Pad (Green)', 'pack', 'Restorative & Cosmetic'),
    ('Optrasculpt Pad (Green) /piece', 'piece', 'Restorative & Cosmetic'),
    ('Orafil G (Green)', 'bottle', 'Restorative & Cosmetic'),
    ('Orafil Plus (Fermin)', '', 'Restorative & Cosmetic'),
    ('Orafil Plus (Temporary Filling)', 'piece', 'Restorative & Cosmetic'),
    ('Permaseal', 'piece', 'Restorative & Cosmetic'),
    ('Polishing Burs (Rubber)', 'piece', 'Restorative & Cosmetic'),
    ('Polishing Disc', 'set', 'Restorative & Cosmetic'),
    ('Polishing Strip', 'set', 'Restorative & Cosmetic'),
    ('Porcelain Etch', 'syringe', 'Restorative & Cosmetic'),
    ('Rotating Wedge', 'stick', 'Restorative & Cosmetic'),
    ('Silicone Lowspeed Burs (Blue) 10pcs', 'pack', 'Restorative & Cosmetic'),
    ('Silicone Lowspeed Burs (Pink) 10pcs', 'pack', 'Restorative & Cosmetic'),
    ('Temporary Composite (China Brand) A2', 'tube', 'Restorative & Cosmetic'),
    ('Temporary Composite (China Brand) A3', 'tube', 'Restorative & Cosmetic'),
    ('Temporary Composite (China Brand) A3.5', 'tube', 'Restorative & Cosmetic'),
    ('Wedge (Blue)', 'pack', 'Restorative & Cosmetic'),
    ('Wedge (Green)', 'pack', 'Restorative & Cosmetic'),
    ('Wedge (Purple)', 'pack', 'Restorative & Cosmetic'),
    ('Wedge (Yellow)', 'pack', 'Restorative & Cosmetic'),
    ('White Stone (1 set)', 'set', 'Restorative & Cosmetic'),
    ('White Stone (Flame)', 'piece', 'Restorative & Cosmetic'),
    ('White Stone (Pear)', 'piece', 'Restorative & Cosmetic'),
    ('White Stone (Round)', 'piece', 'Restorative & Cosmetic'),
    ('Absorbent Paper #15-40 .02', 'set', 'Endodontic (Root Canal)'),
    ('Absorbent Paper #15-40 .04', 'set', 'Endodontic (Root Canal)'),
    ('Absorbent Paper #15-40 .06', 'set', 'Endodontic (Root Canal)'),
    ('Absorbent Paper #45-80 .02', 'set', 'Endodontic (Root Canal)'),
    ('Absorbent Paper #45-80 .04', 'set', 'Endodontic (Root Canal)'),
    ('Absorbent Paper #45-80 .06', 'set', 'Endodontic (Root Canal)'),
    ('Absorbent Paper Point F1 (Yellow)', 'set', 'Endodontic (Root Canal)'),
    ('Absorbent Paper Point F1-F3', 'set', 'Endodontic (Root Canal)'),
    ('Absorbent Paper Point F2 (Red)', 'set', 'Endodontic (Root Canal)'),
    ('Absorbent Paper Point F3 (Blue)', 'set', 'Endodontic (Root Canal)'),
    ('C-Pilot File #10 (Purple)', 'set', 'Endodontic (Root Canal)'),
    ('C-Pilot File #10 (Purple) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('C-Pilot File #15 (White)', 'set', 'Endodontic (Root Canal)'),
    ('C-Pilot File #15 (White) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('C-Pilot File #6 (Pink)', 'set', 'Endodontic (Root Canal)'),
    ('C-Pilot File #6 (Pink) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('C-Pilot File #8 (Gray)', 'set', 'Endodontic (Root Canal)'),
    ('C-Pilot File #8 (Gray) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('Chlor X Liquid', 'bottle', 'Endodontic (Root Canal)'),
    ('E-Flex S Endo Rotary File (25mm)', 'set', 'Endodontic (Root Canal)'),
    ('E-Flex S Endo Rotary File (31mm)', 'set', 'Endodontic (Root Canal)'),
    ('Edta Gel', 'syringe', 'Endodontic (Root Canal)'),
    ('Edta Liquid', 'bottle', 'Endodontic (Root Canal)'),
    ('Edta Liquid 15ml', 'bottle', 'Endodontic (Root Canal)'),
    ('Endo Activator Tip (Green)', 'set', 'Endodontic (Root Canal)'),
    ('Endo Activator Tip (Red)', 'set', 'Endodontic (Root Canal)'),
    ('Endo Activator Tip (White)', 'set', 'Endodontic (Root Canal)'),
    ('Endo Barbed Broaches #0 52mm', 'piece', 'Endodontic (Root Canal)'),
    ('Endo Barbed Broaches 21mm (Asst.)', 'piece', 'Endodontic (Root Canal)'),
    ('Endo Burs (Round)', 'piece', 'Endodontic (Root Canal)'),
    ('Endo Burs (Straight)', 'piece', 'Endodontic (Root Canal)'),
    ('Endo Fiber Post', 'set', 'Endodontic (Root Canal)'),
    ('Endo Hand File (Protaper)', 'set', 'Endodontic (Root Canal)'),
    ('Endo Needle (Yellow)', 'pack', 'Endodontic (Root Canal)'),
    ('Endo Scaler Tip', 'piece', 'Endodontic (Root Canal)'),
    ('Endo Sealer (AH Plus)', 'set', 'Endodontic (Root Canal)'),
    ('Endo Sealer (Onefil Bioceramic)', 'syringe', 'Endodontic (Root Canal)'),
    ('Endo Sponge', 'box', 'Endodontic (Root Canal)'),
    ('Endo Sponge /piece', 'piece', 'Endodontic (Root Canal)'),
    ('Endo Suction Micro Tip', 'pack', 'Endodontic (Root Canal)'),
    ('Endo Suction Micro Tip /piece', 'piece', 'Endodontic (Root Canal)'),
    ('Endo Suction Tip', 'pack', 'Endodontic (Root Canal)'),
    ('Endo Suction Tip /piece', 'piece', 'Endodontic (Root Canal)'),
    ('Eucalyptus Oil', 'bottle', 'Endodontic (Root Canal)'),
    ('Gates Glidden', 'set', 'Endodontic (Root Canal)'),
    ('Gutta Percha .04 F1-F3', 'set', 'Endodontic (Root Canal)'),
    ('Gutta Percha .04 F2 (Red)', 'set', 'Endodontic (Root Canal)'),
    ('Gutta Percha .4 (Yellow)', 'set', 'Endodontic (Root Canal)'),
    ('Gutta Percha 04. F3 (Blue)', 'set', 'Endodontic (Root Canal)'),
    ('Gutta Percha GreatTaper .04 #15-40', 'set', 'Endodontic (Root Canal)'),
    ('Gutta Percha GreatTaper .04 #45-80', 'set', 'Endodontic (Root Canal)'),
    ('Hypochlorite', 'gallon', 'Endodontic (Root Canal)'),
    ('K-File NITI #10 (Purple) 21mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #10 (Purple) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #10 (Purple) 25mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #10 (Purple) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #10 (Purple) 28mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #10 (Purple) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #10 (Purple) 31mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #10 (Purple) 31mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #15 (Gray) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-FILE NITI #15 (Gray) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #15 (Gray) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #15 (White) 21mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #15 (White) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-FIle NITI #15 (White) 25mm', 'set', 'Endodontic (Root Canal)'),
    ('K-FIle NITI #15 (White) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #15 (White) 28mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #15 (White) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #15 (White) 31mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #15 (White) 31mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #15-40 (21mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #15-40 (21mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #15-40 (25mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #15-40 (25mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #15-40 (28mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #15-40 (28mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #15-40 (31mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #15-40 (31mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #45-80 (21mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #45-80 (21mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #45-80 (25mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #45-80 (25mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #45-80 (28mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #45-80 (28mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #45-80 (31mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #45-80 (31mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #6 (Pink) 21mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #6 (Pink) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #6 (Pink) 25mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #6 (Pink) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #6 (Pink) 28mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #6 (Pink) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #6 (Pink) 31mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #6 (Pink) 31mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #8 (Gray) 21mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #8 (Gray) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #8 (Gray) 25mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #8 (Gray) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #8 (Gray) 28mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #8 (Gray) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File NITI #8 (Gray) 31mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File NITI #8 (Gray) 31mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #10 (Purple) 21mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #10 (Purple) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #10 (Purple) 25mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #10 (Purple) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #10 (Purple) 28mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #10 (Purple) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #10 (Purple) 31mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #10 (Purple) 31mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15 (Gray) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15 (Gray) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15 (Gray) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15 (White) 21mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #15 (White) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-FIle SS #15 (White) 25mm', 'set', 'Endodontic (Root Canal)'),
    ('K-FIle SS #15 (White) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15 (White) 28mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #15 (White) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15 (White) 31mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #15 (White) 31mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15-40 (21mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #15-40 (21mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15-40 (25mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #15-40 (25mm) piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15-40 (28mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #15-40 (28mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #15-40 (31mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #15-40 (31mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #45-80 (21mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #45-80 (21mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #45-80 (25mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #45-80 (25mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #45-80 (28mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #45-80 (28mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #45-80 (31mm)', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #45-80 (31mm) /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #6 (Pink) 21mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #6 (Pink) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #6 (Pink) 25mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #6 (Pink) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #6 (Pink) 28mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #6 (Pink) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #6 (Pink) 31mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #6 (Pink) 31mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #8 (Gray) 21mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #8 (Gray) 21mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #8 (Gray) 25mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #8 (Gray) 25mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #8 (Gray) 28mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #8 (Gray) 28mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('K-File SS #8 (Gray) 31mm', 'set', 'Endodontic (Root Canal)'),
    ('K-File SS #8 (Gray) 31mm /piece', 'piece', 'Endodontic (Root Canal)'),
    ('MTA', 'syringe', 'Endodontic (Root Canal)'),
    ('Opalescence Endo', 'syringe', 'Endodontic (Root Canal)'),
    ('Peeso Rimer', 'set', 'Endodontic (Root Canal)'),
    ('Quicks/ Spacer', 'tube', 'Endodontic (Root Canal)'),
    ('Rubber Dam', 'box', 'Endodontic (Root Canal)'),
    ('Rubber Dam Template', 'sheet', 'Endodontic (Root Canal)'),
    ('Well Paste', 'syringe', 'Endodontic (Root Canal)'),
    ('Acrylic Liquid Self-Cure (120ml)', 'bottle', 'Prosthodontic & Impression'),
    ('Acrylic Liquid Self-Cure (240ml)', 'bottle', 'Prosthodontic & Impression'),
    ('Acrylic Powder Pink Self-Cure (120g)', 'pack', 'Prosthodontic & Impression'),
    ('Acrylic Powder Pink Self-Cure (21g)', 'pack', 'Prosthodontic & Impression'),
    ('Acrylic Powder White Self-Cure (120g)', 'pack', 'Prosthodontic & Impression'),
    ('Acrylic Powder White Self-Cure (21g)', 'pack', 'Prosthodontic & Impression'),
    ('Alginate (Dentflex)', 'bottle', 'Prosthodontic & Impression'),
    ('Alginate (Tropicalgin)', 'pack', 'Prosthodontic & Impression'),
    ('Bite Tip Big (Blue)', 'pack', 'Prosthodontic & Impression'),
    ('Bite Wax (Yellow)', 'piece', 'Prosthodontic & Impression'),
    ('Care C&B Temporary Resin A2', 'piece', 'Prosthodontic & Impression'),
    ('CharmFlex Bite Fast (Green)', 'piece', 'Prosthodontic & Impression'),
    ('CharmFlex Heavy (Blue)', 'tube', 'Prosthodontic & Impression'),
    ('CharmFlex Light Body (Orange)', 'tube', 'Prosthodontic & Impression'),
    ('CharmTemp Crown Temporary Resin A2', 'piece', 'Prosthodontic & Impression'),
    ('Cord 0', 'bottle', 'Prosthodontic & Impression'),
    ('Cord 00', 'bottle', 'Prosthodontic & Impression'),
    ('Cord 000', 'bottle', 'Prosthodontic & Impression'),
    ('Cord 1', 'bottle', 'Prosthodontic & Impression'),
    ('Cord 2', 'bottle', 'Prosthodontic & Impression'),
    ('False Teeth Beads', 'pack', 'Prosthodontic & Impression'),
    ('Green Stick', 'piece', 'Prosthodontic & Impression'),
    ('Impression Tip (Yellow)', 'piece', 'Prosthodontic & Impression'),
    ('Impression Tip Big (Blue)', 'piece', 'Prosthodontic & Impression'),
    ('Impression Tip Small (Yellow)', 'pack', 'Prosthodontic & Impression'),
    ('Impression Tip with Micro Tip (White)', 'piece', 'Prosthodontic & Impression'),
    ('Impression Tray (Assorted)', 'set', 'Prosthodontic & Impression'),
    ('Soft Liner', 'set', 'Prosthodontic & Impression'),
    ('Vonflex S Bite (Blue)', 'piece', 'Prosthodontic & Impression'),
    ('Vonflex S Light (Pink)', 'piece', 'Prosthodontic & Impression'),
    ('Vonflex S Putty and Catalyst Big', 'set', 'Prosthodontic & Impression'),
    ('Vonflex S Putty and Catalyst Mini', 'set', 'Prosthodontic & Impression'),
    ('Zetaplus (Zhermack)', 'set', 'Prosthodontic & Impression'),
    ('Betadine', 'bottle', 'Surgical, Periodontal & Implant'),
    ('Bone Graph Granules', 'piece', 'Surgical, Periodontal & Implant'),
    ('Hemostal', 'bottle', 'Surgical, Periodontal & Implant'),
    ('Impant Body', 'piece', 'Surgical, Periodontal & Implant'),
    ('Implant Healing Abutment', 'piece', 'Surgical, Periodontal & Implant'),
    ('Implant Scan Body', 'piece', 'Surgical, Periodontal & Implant'),
    ('Implant Screw', 'piece', 'Surgical, Periodontal & Implant'),
    ('Sodium Chloride (NSS)', 'liter', 'Surgical, Periodontal & Implant'),
    ('Surgical Blade #12 (100pcs)', 'box', 'Surgical, Periodontal & Implant'),
    ('Surgical Blade #12 /piece', 'piece', 'Surgical, Periodontal & Implant'),
    ('Surgical Blade (#15)', 'box', 'Surgical, Periodontal & Implant'),
    ('Surgical Silk Suture Thread', 'roll', 'Surgical, Periodontal & Implant'),
    ('Surgical Suction Tip', 'piece', 'Surgical, Periodontal & Implant'),
    ('Surgical Suction Tip /box', 'box', 'Surgical, Periodontal & Implant'),
    ('Surgical Suture Needle', 'pack', 'Surgical, Periodontal & Implant'),
    ("Surgical Suture Non-Resorbable (Blue) 10's", 'box', 'Surgical, Periodontal & Implant'),
    ("Surgical Suture Resorbable (Brown) 10's", 'box', 'Surgical, Periodontal & Implant'),
    ('Surgical Thread Resorbable BROWN 26mm (TUDOR) /piece', 'piece', 'Surgical, Periodontal & Implant'),
    ('16x16 SS Lower', 'pack', 'Orthodontic'),
    ('Buccaltube 2nd Molar', 'pack', 'Orthodontic'),
    ('Buccaltube Convertible', 'set', 'Orthodontic'),
    ('Buccaltube Non-Convertible', 'set', 'Orthodontic'),
    ('Ceramic Bracket', 'set', 'Orthodontic'),
    ('Chain', 'roll', 'Orthodontic'),
    ('Coil Spring', 'pack', 'Orthodontic'),
    ('Crimpable Hook', 'pack', 'Orthodontic'),
    ('Elastic Placer (Locator Hook)', 'pack', 'Orthodontic'),
    ('Elastics Chipmunk 1x8 (3.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Chipmunk 1x8 (4.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Chipmunk 1x8 (6.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Fox 1x4 (3.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Fox 1x4 (4.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Fox 1x4 (6.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Monkey 3x8 (3.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Monkey 3x8 (4.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Monkey 3x8 (6.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Penguin 5x16 (3.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Penguin 5x16 (4.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Penguin 5x16 (6.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Rabbit 3x16 (3.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Rabbit 3x16 (4.5oz)', 'pack', 'Orthodontic'),
    ('Elastics Rabbit 3x16 (6.5oz)', 'pack', 'Orthodontic'),
    ('Ligaties/ Rubber', 'pack', 'Orthodontic'),
    ('Ligature Wire #20', 'roll', 'Orthodontic'),
    ('Ligature Wire #25', 'roll', 'Orthodontic'),
    ('Ligature Wire #30', 'roll', 'Orthodontic'),
    ('Lingual Button', 'pack', 'Orthodontic'),
    ('Metal Bracket (Roth 18 Standard)', 'set', 'Orthodontic'),
    ('Metal Bracket (Roth 22)', 'set', 'Orthodontic'),
    ('Molar Band', 'set', 'Orthodontic'),
    ('Molar Band Convertible', 'set', 'Orthodontic'),
    ('Molar Separator', 'pack', 'Orthodontic'),
    ('Occlusal Band Cement (Blue)', 'tube', 'Orthodontic'),
    ('Ortho Activity Crimpable Hook (Left & Right)', 'pack', 'Orthodontic'),
    ('Ortho Composite (Den Fil)', 'tube', 'Orthodontic'),
    ('Ortho Composite (Neofil)', 'piece', 'Orthodontic'),
    ('Ortho Direct Bond Eyelet (10x1mm)', 'pack', 'Orthodontic'),
    ('Ortho Sliding Crimpable Hook (Left 5.4mm)', 'pack', 'Orthodontic'),
    ('Ortho Sliding Crimpable Hook (Right 5.4mm)', 'pack', 'Orthodontic'),
    ('Ortho Torque Spring 10x1mm (small)', 'pack', 'Orthodontic'),
    ('Ortho Torque Spring 17x25 (small)', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 12 NITI Lower', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 12 NITI Upper', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 14 NITI Lower', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 14 NITI Upper', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 16 NITI Lower', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 16 NITI Upper', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 18 NITI Lower', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 18 NITI Upper', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 20 NITI Lower', 'pack', 'Orthodontic'),
    ('Reverse Curve Wire 20 NITI Upper', 'pack', 'Orthodontic'),
    ('Saphire Bracket', 'set', 'Orthodontic'),
    ('Self Ligating Bracket', 'set', 'Orthodontic'),
    ('Straight Wire 17x15 SS', 'pack', 'Orthodontic'),
    ('Torque Spring (Medium)', 'pack', 'Orthodontic'),
    ('Torque Spring (Small)', 'pack', 'Orthodontic'),
    ('Wire 12 NITI Lower', 'pack', 'Orthodontic'),
    ('Wire 12 NITI Upper', 'pack', 'Orthodontic'),
    ('Wire 12 SS Lower', 'pack', 'Orthodontic'),
    ('Wire 12 SS LOWER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 12 SS Upper', 'pack', 'Orthodontic'),
    ('Wire 12 SS UPPER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 14 NITI Lower', 'pack', 'Orthodontic'),
    ('Wire 14 NITI Upper', 'pack', 'Orthodontic'),
    ('Wire 14 SS Lower', 'pack', 'Orthodontic'),
    ('Wire 14 SS LOWER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 14 SS Upper', 'pack', 'Orthodontic'),
    ('Wire 14 SS UPPER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 16 NITI Lower', 'pack', 'Orthodontic'),
    ('Wire 16 NITI Upper', 'pack', 'Orthodontic'),
    ('Wire 16 SS Lower', 'pack', 'Orthodontic'),
    ('Wire 16 SS LOWER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 16 SS Upper', 'pack', 'Orthodontic'),
    ('Wire 16 SS UPPER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 16x16 NITI Lower', 'pack', 'Orthodontic'),
    ('Wire 16x16 NITI Upper', 'pack', 'Orthodontic'),
    ('Wire 16x16 SS Lower', 'pack', 'Orthodontic'),
    ('Wire 16x16 SS Upper', 'pack', 'Orthodontic'),
    ('Wire 16x22 NITI Lower', 'pack', 'Orthodontic'),
    ('Wire 16x22 NITI Upper', 'pack', 'Orthodontic'),
    ('Wire 16x22 SS Lower', 'pack', 'Orthodontic'),
    ('Wire 16x22 SS Upper', 'pack', 'Orthodontic'),
    ('Wire 17x25 NITI Lower', 'pack', 'Orthodontic'),
    ('Wire 17x25 NITI Upper', 'pack', 'Orthodontic'),
    ('Wire 17x25 SS Lower', 'pack', 'Orthodontic'),
    ('Wire 17x25 SS LOWER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 17x25 SS Upper', 'pack', 'Orthodontic'),
    ('Wire 17x25 SS UPPER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 18 NITI Lower', 'pack', 'Orthodontic'),
    ('Wire 18 NITI Upper', 'pack', 'Orthodontic'),
    ('Wire 18 SS Lower', 'pack', 'Orthodontic'),
    ('Wire 18 SS LOWER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 18 SS Upper', 'pack', 'Orthodontic'),
    ('Wire 18 SS UPPER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 19x25 NITI Lower', 'pack', 'Orthodontic'),
    ('Wire 19x25 NITI Upper', 'pack', 'Orthodontic'),
    ('Wire 19x25 SS Lower', 'pack', 'Orthodontic'),
    ('Wire 19x25 SS Upper', 'pack', 'Orthodontic'),
    ('Wire 20 NITI Lower', 'pack', 'Orthodontic'),
    ('Wire 20 NITI Upper', 'pack', 'Orthodontic'),
    ('Wire 20 SS Lower', 'pack', 'Orthodontic'),
    ('Wire 20 SS LOWER (Natural)', 'pack', 'Orthodontic'),
    ('Wire 20 SS Upper', 'pack', 'Orthodontic'),
    ('Wire 20 SS UPPER (Natural)', 'pack', 'Orthodontic'),
    ('Alcohol', 'gallon', 'Infection Control & PPE'),
    ('Clingwrap', 'roll', 'Infection Control & PPE'),
    ('Counter Plastic Bag', 'pack', 'Infection Control & PPE'),
    ('Disposable Plastic Gloves Small', 'pack', 'Infection Control & PPE'),
    ('Facemask', 'pack', 'Infection Control & PPE'),
    ("Faceshield Film (10's)", 'pack', 'Infection Control & PPE'),
    ('Gloves GLOMED (Large) Black per box', 'box', 'Infection Control & PPE'),
    ('Gloves GLOMED (Medium) Black per box', 'box', 'Infection Control & PPE'),
    ('Gloves INDOPLAS (Small) per box', 'box', 'Infection Control & PPE'),
    ('Gloves INDOPLAS (XS) per box', 'box', 'Infection Control & PPE'),
    ('Gloves SMALL (Glomed) 10bxs', 'box', 'Infection Control & PPE'),
    ('Gloves SMALL (Indoplas) 10bxs', 'box', 'Infection Control & PPE'),
    ('Gloves XS (Indoplas) 10bxs', 'box', 'Infection Control & PPE'),
    ('Hand soap Pump Bottle', 'piece', 'Infection Control & PPE'),
    ('Handwash', 'gallon', 'Infection Control & PPE'),
    ('Headcap', 'pack', 'Infection Control & PPE'),
    ('Hydrogen Peroxide (Agua)', 'gallon', 'Infection Control & PPE'),
    ('Johnson Baby Powder 500g', 'grams', 'Infection Control & PPE'),
    ('Patient PPE for Adult (White)', 'piece', 'Infection Control & PPE'),
    ('Patient PPE for LUX (Blue)', 'piece', 'Infection Control & PPE'),
    ('Patient PPE for Pedo (White)', 'piece', 'Infection Control & PPE'),
    ('PPE (Px)', 'piece', 'Infection Control & PPE'),
    ('Spray Bottle', 'piece', 'Infection Control & PPE'),
    ('Anesthesia (Articaine)', 'box', 'Anesthetics & Pharmaceuticals'),
    ('Anesthesia (ARTICAINE) /carpsule', 'piece', 'Anesthetics & Pharmaceuticals'),
    ('Anesthesia (Lidocaine)', 'box', 'Anesthetics & Pharmaceuticals'),
    ('Anesthesia (LIDOCAINE) /carpule', 'piece', 'Anesthetics & Pharmaceuticals'),
    ('Anesthesia (Mepivacaine)', 'box', 'Anesthetics & Pharmaceuticals'),
    ('Anesthesia (MEPIVACAINE) /carpule', 'piece', 'Anesthetics & Pharmaceuticals'),
    ('Anesthetic Spray (Zeyco)', 'bottle', 'Anesthetics & Pharmaceuticals'),
    ('Disposable Syringe (50ml)', 'piece', 'Anesthetics & Pharmaceuticals'),
    ('Disposable Syringe 1ml', 'box', 'Anesthetics & Pharmaceuticals'),
    ('Disposable Syringe 5ml', 'box', 'Anesthetics & Pharmaceuticals'),
    ('Needle Long', 'box', 'Anesthetics & Pharmaceuticals'),
    ('Needle Small', 'box', 'Anesthetics & Pharmaceuticals'),
    ('Needle XS', 'box', 'Anesthetics & Pharmaceuticals'),
    ('Topical Anesthesia Spray (Zeyco)', 'bottle', 'Anesthetics & Pharmaceuticals'),
    ('Acrylic Liquid Dropper', 'piece', 'Laboratory Consumables'),
    ('Cement (Castone)', 'pack', 'Laboratory Consumables'),
    ('Cement (Diestone)', 'pack', 'Laboratory Consumables'),
    ('Cement (Plaster)', 'pack', 'Laboratory Consumables'),
    ('Denatured Alcohol', 'liter', 'Laboratory Consumables'),
    ('Low Speed Bur', 'set', 'Laboratory Consumables'),
    ('Moldgard Liquid (120ml)', 'bottle', 'Laboratory Consumables'),
    ('Pink Wax', 'piece', 'Laboratory Consumables'),
    ('Pumice Powder (Rough)', 'pack', 'Laboratory Consumables'),
    ('Pumice Powder (Smooth)', 'pack', 'Laboratory Consumables'),
    ('Sticky Wax', 'piece', 'Laboratory Consumables'),
    ('Thermoplastic Sheet 1mm (Hard) for SPLINT', 'pack', 'Laboratory Consumables'),
    ('Thermoplastic Sheet 1mm (Hard) for SPLINT /piece', 'piece', 'Laboratory Consumables'),
    ('Thermoplastic Sheet 1mm (Soft) for MOUTHGUARD', 'pack', 'Laboratory Consumables'),
    ('Thermoplastic Sheet 1mm (Soft) for MOUTHGUARD /piece', 'piece', 'Laboratory Consumables'),
    ('Dental Floss (Small)', 'piece', 'Patient Take-home Items'),
    ('Denture Bath', 'box', 'Patient Take-home Items'),
    ('Embrace It Mouthwash (Hyl it)', 'piece', 'Patient Take-home Items'),
    ('Gumtech Mouthwash (Blue)', 'piece', 'Patient Take-home Items'),
    ('Gumtech Mouthwash (Red)', 'piece', 'Patient Take-home Items'),
    ('Gumtech Toothpaste (Blue)', 'piece', 'Patient Take-home Items'),
    ('Gumtech Toothpaste (Red)', 'piece', 'Patient Take-home Items'),
    ('ORAHEX 50ml', 'bottle', 'Patient Take-home Items'),
    ('Ortho Kit', 'set', 'Patient Take-home Items'),
    ('Ortho Toothbrush', 'piece', 'Patient Take-home Items'),
    ('Ortho Wax', 'piece', 'Patient Take-home Items'),
    ('Retainer Box', 'box', 'Patient Take-home Items'),
    ('Retainer box /piece', 'piece', 'Patient Take-home Items'),
    ('Sticker (Boys)', 'piece', 'Patient Take-home Items'),
    ('Sticker (Girls)', 'piece', 'Patient Take-home Items'),
    ('Stress Ball', 'piece', 'Patient Take-home Items'),
    ('Toothbrush (Adult)', 'piece', 'Patient Take-home Items'),
    ('Toothbrush (Kids)', 'piece', 'Patient Take-home Items'),
    ('Carving Blade', 'piece', 'Instruments & Small Equipment'),
    ('Cheek Retractor (C Shape)', 'piece', 'Instruments & Small Equipment'),
    ('Cord Packer', 'piece', 'Instruments & Small Equipment'),
    ('Dental Chair Self Tray Table', 'piece', 'Instruments & Small Equipment'),
    ('Dental Chair Timer', 'piece', 'Instruments & Small Equipment'),
    ('Egg and Ball Burnisher', 'piece', 'Instruments & Small Equipment'),
    ('Face Mirror', 'piece', 'Instruments & Small Equipment'),
    ('Fox Plane', 'piece', 'Instruments & Small Equipment'),
    ('Handpiece Oil (SKI)', 'bottle', 'Instruments & Small Equipment'),
    ('Impression Tray (Metal)', 'set', 'Instruments & Small Equipment'),
    ('Ligature Wire Cutter', 'piece', 'Instruments & Small Equipment'),
    ('Lighter', 'piece', 'Instruments & Small Equipment'),
    ('Mathieu Plier', 'piece', 'Instruments & Small Equipment'),
    ('Mouth Mirror', 'piece', 'Instruments & Small Equipment'),
    ('Mouth MIRROR (MIRROR ONLY) /piece', 'piece', 'Instruments & Small Equipment'),
    ("Mouth Mirror Mirror ONLY (10's)", 'box', 'Instruments & Small Equipment'),
    ('Pulse Oximeter', 'piece', 'Instruments & Small Equipment'),
    ('Restoration Instruments (ASST. SET)', 'set', 'Instruments & Small Equipment'),
    ('Shade Guide (Big)', 'set', 'Instruments & Small Equipment'),
    ('Shade Guide (Small)', 'set', 'Instruments & Small Equipment'),
    ('Small Tray', 'piece', 'Instruments & Small Equipment'),
    ('Surgical Scissor', 'piece', 'Instruments & Small Equipment'),
    ('1/4 Index Card Patient Record (100pcs)', 'pack', 'Office & Admin Supplies'),
    ('Ballpen (Black) 12pcs', 'box', 'Office & Admin Supplies'),
    ('Ballpen (Black) 50pcs', 'box', 'Office & Admin Supplies'),
    ('Ballpen (Red) 12pcs', 'box', 'Office & Admin Supplies'),
    ('Ballpen /piece (Black)', 'piece', 'Office & Admin Supplies'),
    ('Ballpen /piece (Red)', 'piece', 'Office & Admin Supplies'),
    ('Battery AA', 'pack', 'Office & Admin Supplies'),
    ('Battery AAA', 'pack', 'Office & Admin Supplies'),
    ('Bond Paper A4', 'rim', 'Office & Admin Supplies'),
    ('Bond Paper Long', 'rim', 'Office & Admin Supplies'),
    ('Bond Paper Short/Letter', 'rim', 'Office & Admin Supplies'),
    ('Brown Envelope (Long)', 'piece', 'Office & Admin Supplies'),
    ('Calculator', 'piece', 'Office & Admin Supplies'),
    ('Charger Connecting Cord (Micro USB)', 'piece', 'Office & Admin Supplies'),
    ('Charger Connecting Cord (Type C)', 'piece', 'Office & Admin Supplies'),
    ('Charger Type C with Adapter', 'set', 'Office & Admin Supplies'),
    ('Clear Acrylic Organizer', 'set', 'Office & Admin Supplies'),
    ('Correction Tape', 'piece', 'Office & Admin Supplies'),
    ('Cutter (Blade)', 'set', 'Office & Admin Supplies'),
    ('Double Sided Tape', 'piece', 'Office & Admin Supplies'),
    ('Flash Drive (Toshiba)', 'piece', 'Office & Admin Supplies'),
    ('Laminating Film A4 (100s)', 'pack', 'Office & Admin Supplies'),
    ('Log Book (300s)', 'piece', 'Office & Admin Supplies'),
    ('Masking Tape', 'piece', 'Office & Admin Supplies'),
    ('Mighty Bond', 'piece', 'Office & Admin Supplies'),
    ('Notebook (Mini)', 'piece', 'Office & Admin Supplies'),
    ('Packing Tape', 'piece', 'Office & Admin Supplies'),
    ('Permanent Marker (12pcs)', 'box', 'Office & Admin Supplies'),
    ('Permanent Marker (Black)', 'piece', 'Office & Admin Supplies'),
    ('Photo Paper (MATTE) QUAFF', 'pack', 'Office & Admin Supplies'),
    ('Photo Paper A4 Glossy (Quaff)', 'pack', 'Office & Admin Supplies'),
    ('Printer Ink (Black)', 'bottle', 'Office & Admin Supplies'),
    ('Printer Ink (Cyan)', 'bottle', 'Office & Admin Supplies'),
    ('Printer Ink (Magenta)', 'bottle', 'Office & Admin Supplies'),
    ('Printer Ink (Yellow)', 'bottle', 'Office & Admin Supplies'),
    ('Rubber Band', 'pack', 'Office & Admin Supplies'),
    ('Scissors (Big)', 'piece', 'Office & Admin Supplies'),
    ('Scotch Tape', 'piece', 'Office & Admin Supplies'),
    ('Staple Wire', 'box', 'Office & Admin Supplies'),
    ('Sticker Paper A4', 'pack', 'Office & Admin Supplies'),
    ('Sticky Note', 'pad', 'Office & Admin Supplies'),
    ('Tape Dispenser', 'piece', 'Office & Admin Supplies'),
    ('White Board Marker (Black)', 'piece', 'Office & Admin Supplies'),
    ('Zip Lock (Big)', 'pack', 'Office & Admin Supplies'),
    ('Zip Lock (Extra Small)', 'pack', 'Office & Admin Supplies'),
    ('Zip Lock (Small)', 'pack', 'Office & Admin Supplies'),
    ('Floor Mop', 'set', 'Housekeeping'),
    ('Glade (Air freshiner)', 'bottle', 'Housekeeping'),
    ('Oil Base Perfume (for humidifier)', 'gallon', 'Housekeeping'),
    ('Sampayan', 'set', 'Housekeeping'),
]
