"""Digital Solutions Dental Laboratory (DSDL) price list, from the lab's printed price list (October 2026).
Loaded once into Laboratory -> Price list; the lab edits prices there afterwards.
(category, name, price in pesos, unit label shown after the price, note)"""

DSDL_PRICES = [
    ("Denture processing", "Flexible", 3800, "", ""),
    ("Denture processing", "Ivocap", 5665, "", "With Ivobase denture injector machine"),
    ("Denture", "Ordinary full", 2110, "", ""),
    ("Denture", "Ordinary partial", 1770, "", ""),
    ("Denture", "Lucitone", 2500, "", ""),
    ("Denture", "Basis High", 3000, "", ""),
    ("Pontic", "New Ace", 300, "per arch", ""),
    ("Pontic", "New Ace PX", 500, "per arch", ""),
    ("Pontic", "Natura tone", 500, "per arch", ""),
    ("Zirconia", "Zirconia premium", 5500, "per unit", "Crown, veneer, bridge, inlay and onlay"),
    ("Lithium disilicate", "Lithium disilicate premium", 5500, "", "Crown, veneer, bridge, inlay and onlay"),
    ("3D printed (permanent)", "3D printed crown", 3500, "", ""),
    ("3D printed (permanent)", "3D printed inlay / onlay / overlay", 3500, "", ""),
    ("3D printed (permanent)", "3D printed fixed bridge", 3500, "", "Up to 3 units only"),
    ("3D printed (temporary)", "Temporary 3D printed crown", 650, "", ""),
    ("3D printed (temporary)", "Temporary 3D printed fixed bridge", 650, "", ""),
    ("Milled PMMA", "Milled PMMA crown", 3500, "", ""),
    ("Milled PMMA", "Milled PMMA inlay / onlay", 3500, "", ""),
    ("Milled PMMA", "Milled PMMA fixed bridge", 3500, "", "Up to 3 units only"),
    ("Porcelain fused to zirconia", "Porcelain fused to zirconia", 6500, "", "Crown, veneer, bridge, inlay and onlay"),
    ("3D printed cast", "Model cast", 500, "", ""),
    ("3D printed cast", "Ortho cast / study cast with palate", 600, "", ""),
    ("3D printed ortho retainer", "3D printed mouth guard", 3000, "", ""),
    ("3D printed ortho retainer", "3D printed splint", 3000, "", ""),
    ("Forming machine", "Invisible retainer", 880, "", ""),
    ("Forming machine", "Splint (forming machine)", 880, "", ""),
    ("Forming machine", "Mouth guard (forming machine)", 880, "", ""),
    ("Orthodontic appliance", "Hawley retainer", 1000, "", ""),
    ("Orthodontic appliance", "Wrap around retainer", 1300, "", ""),
    ("Orthodontic appliance", "Bleaching tray", 600, "per unit", ""),
    ("Orthodontic appliance", "Nance appliance", 1000, "", ""),
    ("Orthodontic appliance", "Occlusal splint (acrylic)", 1200, "", ""),
    ("Additional services", "Individual tray", 300, "per arch", ""),
    ("Additional services", "Additional wire clasp", 500, "per arch", ""),
    ("Additional services", "Denture rebase", 1000, "", ""),
    ("Additional services", "Denture relining", 1000, "", ""),
    ("Additional services", "Denture cleaning", 1000, "", ""),
    ("Additional services", "Mock-up design", 250, "per unit", ""),
    ("Additional services", "Digital scan", 5500, "", ""),
    ("Additional services", "Crack repair", 700, "", ""),
    ("Additional services", "Occlusion rim", 300, "per arch", ""),
    ("Additional services", "1-way expander", 1500, "per arch", ""),
    ("Additional services", "2-way expander", 2500, "per arch", ""),
    ("Additional services", "3-way expander", 3500, "per arch", ""),
    ("Additional services", "Diagnostic cast", 300, "per arch", ""),
    ("Additional services", "Rush fee (denture)", 1500, "", ""),
    ("Additional services", "Rush fee (retainer)", 1000, "", ""),
    ("Additional services", "Rush fee (zirconia / Emax)", 5500, "", ""),
]
DSDL_CONTACT = {"address": "Essen Bldg., Paseo del Congreso, Liang, Malolos, Bulacan",
                "phone": "0948 918 2775 / 0955 160 3240", "email": "digitalsolutions.laboratory@gmail.com"}
